package com.bingo.riddle.activity;

import java.util.Timer;
import java.util.TimerTask;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;
import android.graphics.Color;
import android.os.AsyncTask;
import android.os.Bundle;
import android.util.Log;
import android.view.Gravity;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.widget.TextView;

import com.ads.tool.AdsConstants;
import com.bingo.riddle.db.DBRiddleManager;
import com.bingo.riddle.model.Riddle;
import com.bingo.twister.R;
import com.wandoujia.ads.sdk.Ads;

public class FlashActivity extends Activity {
	private Timer timer;

	// private ViewGroup container;

	// 关于数据操作
	private DBRiddleManager dbRManager = null;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		requestWindowFeature(Window.FEATURE_NO_TITLE);
		setContentView(R.layout.activity_splash);

		timer = new Timer();
		TimerTask task = new TimerTask() {

			@Override
			public void run() {
				initView();
			}
		};
		timer.schedule(task, 1000 * 5);

		new AsyncTask<Void, Void, Boolean>() {
			@Override
			protected Boolean doInBackground(Void... params) {
				try {
					Ads.init(FlashActivity.this, AdsConstants.APP_ID,
							AdsConstants.SECRET_KEY);
					return true;
				} catch (Exception e) {
					Log.e("ads-sample", "error", e);
					return false;
				}
			}

			@Override
			protected void onPostExecute(Boolean success) {
				final ViewGroup container = (ViewGroup) findViewById(R.id.splash_container);

				if (success) {
					/**
					 * pre load
					 */
					Ads.preLoad(AdsConstants.BANNER1, Ads.AdFormat.banner);

					/**
					 * add ad views
					 */
					View bannerView = Ads.createBannerView(FlashActivity.this,
							AdsConstants.BANNER1);
					container.addView(bannerView, new ViewGroup.LayoutParams(
							ViewGroup.LayoutParams.MATCH_PARENT,
							ViewGroup.LayoutParams.WRAP_CONTENT));
				} else {
					TextView errorMsg = new TextView(FlashActivity.this);
					errorMsg.setText("欢迎使用脑筋急转弯");
					errorMsg.setTextColor(Color.RED);
					errorMsg.setTextSize(20);
					errorMsg.setGravity(Gravity.CENTER_HORIZONTAL);
					container.addView(errorMsg);
				}
			}
		}.execute();

		// 数据库操作
		/* 开启一个新线程，在新线程里执行耗时的方法 */
		new Thread(new Runnable() {
			public void run() {
				// if(AppInstalledUtil.isAppInstalled(getApplicationContext(),
				// "com.bingo.lattern"))
				// {
				// System.out.println("========已安装！==");
				// }
				// else {
				// initData();
				// }

				SharedPreferences sharedPreferences = getSharedPreferences(
						"share", MODE_PRIVATE);

				boolean isFirstRun = sharedPreferences.getBoolean("isFirstRun",
						true);
				Editor editor = sharedPreferences.edit();

				if (isFirstRun) {
					Log.e("debug", "第一次运行");
					editor.putBoolean("isFirstRun", false);
					editor.commit();
					initData();
				} else {
					Log.e("debug", "不是第一次运行");
				}
				// 耗时的方法
			}
		}).start();

	}

	private void initView() {
		Intent intent = new Intent(FlashActivity.this,
				MainFragmentActivity.class);
		startActivity(intent);

		this.finish();
	}

	private void initData() {
		dbRManager = new DBRiddleManager(this);

		Riddle riddle1 = new Riddle("	实行减肥时，最容易瘦的是哪一个部位？ 	","	 钱包	", "经典"	, "无");
		Riddle riddle2 = new Riddle("	什么东西装玻璃，爱把鼻子当马骑？ 	","	 眼镜	", "经典"	, "无");
		Riddle riddle3 = new Riddle("	一个桥载重80公斤，为什么一个重70公斤的人可以拿两个各重10公斤的球过桥？	","	 颠球走	", "经典"	, "无");
		Riddle riddle4 = new Riddle("	什么书中毛病最多？ 	","	 医书中	", "经典"	, "无");
		Riddle riddle5 = new Riddle("	报纸上登的消息不一定百分之百是真的，但什么消息绝对假不了？	","	 报纸上的年、月、日	", "经典"	, "无");
		Riddle riddle6 = new Riddle("	什么票最值钱也最不值钱？ 	","	 股票	", "经典"	, "无");
		Riddle riddle7 = new Riddle("	一对健康夫妇，为什么生出只有一只右眼的婴儿？ 	","	 每个人都只有一只右眼	", "经典"	, "无");
		Riddle riddle8 = new Riddle("	先有男人，还是先有女人? 	","	 因为男人是先生的，所以叫“先生”	", "经典"	, "无");
		Riddle riddle9 = new Riddle("	什么桥下没水？ 	","	 立交桥	", "经典"	, "无");
		Riddle riddle10 = new Riddle("	来电了怎么办 	","	 看电视呀	", "经典"	, "无");
		Riddle riddle11 = new Riddle("	除了玻璃、瓷器等容易碎的东西要小心轻放外，还有什么东西要小心轻放？ 	","	 屁	", "经典"	, "无");
		Riddle riddle12 = new Riddle("	一个小姑娘在打排球，她发了一个球，可无论谁都接不着，为什麽？	","	 球没发出去，或者球出界了	", "经典"	, "无");
		Riddle riddle13 = new Riddle("	金钟奖、金马奖、金像奖哪个对国家贡献最大？ 	","	 金钟奖(精忠报国)	", "经典"	, "无");
		Riddle riddle14 = new Riddle("	什么书谁也没见过? 	","	 天书	", "经典"	, "无");
		Riddle riddle15 = new Riddle("	你在一年半的时间都不会说话，这段时间你在干什么？ 	","	 刚出生在哭	", "经典"	, "无");
		Riddle riddle16 = new Riddle("	某人有喝一打高粱的酒量，但今晚他只喝了半瓶啤酒就醉了，为什么？	","	 他不久前才刚喝了一打高梁	", "经典"	, "无");
		Riddle riddle17 = new Riddle("	一斤棉花和一斤铁块哪一样比较重？ 	","	 一样重	", "经典"	, "无");
		Riddle riddle18 = new Riddle("	先有鸡还是先有蛋？ 	","	 先有蛋，因为在新华字典里面蛋在鸡的前面	", "经典"	, "无");
		Riddle riddle19 = new Riddle("	考试时应注意什么？	","	 监考老师	", "经典"	, "无");
		Riddle riddle20 = new Riddle("	亚当和夏娃结婚后，最大的遗憾是什么？ 	","	 没有人来喝喜酒	", "经典"	, "无");
		Riddle riddle21 = new Riddle("	明星出入公共场所，最怕遇到什么事？ 	","	 没人找他签名	", "经典"	, "无");
		Riddle riddle22 = new Riddle("	怎么称呼一只不会叫的狗？ 	","	 狗	", "经典"	, "无");
		Riddle riddle23 = new Riddle("	大龙家今晚的电视为什么只有图像，没有声音？ 	","	 上演的是哑剧	", "经典"	, "无");
		Riddle riddle24 = new Riddle("	虽然只是薄薄的一片，女人少了它一天也活不下去的是东西？？ 	","	 镜子	", "经典"	, "无");
		Riddle riddle25 = new Riddle("	小涵捉到一只小鸟，她把小鸟放在桌子上，小鸟却没有飞，是什么原因？	","	 鸟已死	", "经典"	, "无");
		Riddle riddle26 = new Riddle("	五月五日是我国人民传统节日：端午节，是伟大诗人屈原投江的日子，那么你知道五月十二日是什么日子吗? 	","	 屈原烧“头七”的日子	", "经典"	, "无");
		Riddle riddle27 = new Riddle("	我国文化源远流长，唐代有诗，宋代有词，元代有曲，明代有小说，那么现在有什么？	","	 参考书	", "经典"	, "无");
		Riddle riddle28 = new Riddle("	有个人说用牙齿可以判断鸡的年龄，为什么？	","	 牙可以嚼出肉的老嫩	", "经典"	, "无");
		Riddle riddle29 = new Riddle("	除了变色龙以外，什么动物最擅长伪装术? 	","	 人	", "经典"	, "无");
		Riddle riddle30 = new Riddle("	四年级三班是怎样上珠算的？ 	","	 各打各的算盘	", "经典"	, "无");
		Riddle riddle31 = new Riddle("	戴维一家五口外出旅游，说好一人带一瓶饮料可戴维坚持只带4瓶可口可乐，为什么？	","	 还有一瓶是汽水	", "经典"	, "无");
		Riddle riddle32 = new Riddle("	什么样的人物照片你看不出照的是谁? 	","	 X光片	", "经典"	, "无");
		Riddle riddle33 = new Riddle("	第一个登上月球的中国姑娘是谁？ 	","	 嫦娥	", "经典"	, "无");
		Riddle riddle34 = new Riddle("	老王从九岁开始有虫牙，为什么90岁时他的牙都还在？ 	","	 虫早已换掉	", "经典"	, "无");
		Riddle riddle35 = new Riddle("	人身上的什么东西不怕冷? 	","	 鼻涕	", "经典"	, "无");
		Riddle riddle36 = new Riddle("	有一样东西，它每个月都会来一次，只是薄薄的一张纸就令你心烦意乱，这到底是什么东西呢？ 	","	 每个月的成绩单	", "经典"	, "无");
		Riddle riddle37 = new Riddle("	小华说他能在1秒钟之内把房间和房间里的玩具都变没了，这可能吗?	","	 把眼睛闭上	", "经典"	, "无");
		Riddle riddle38 = new Riddle("	世界上人口最多是哪个国家？ 	","	 联合国	", "经典"	, "无");
		Riddle riddle39 = new Riddle("	阿兵哥们为什么会把手榴弹叫做铁蛋？ 	","	 碰上了铁定完蛋	", "经典"	, "无");
		Riddle riddle40 = new Riddle("	向日葵会随着太阳而转动，请问阴天的时候会向着哪里？ 	","	 向着光头的人	", "经典"	, "无");
		Riddle riddle41 = new Riddle("	两只蚂蚁抬根杠，一只蚂蚁杠上望 	","	 六	", "经典"	, "无");
		Riddle riddle42 = new Riddle("	唐老鸭最怕什么事？ 	","	 发现原来自己是白天鹅	", "经典"	, "无");
		Riddle riddle43 = new Riddle("	只有头却没有身体的牛，叫做什么牛？ 	","	 一头牛	", "经典"	, "无");
		Riddle riddle44 = new Riddle("	小偷从现场逃走，为什么没有留下脚印？ 	","	 倒着走的	", "经典"	, "无");
		Riddle riddle45 = new Riddle("	渔夫最怕什么？ 	","	 没人吃鱼	", "经典"	, "无");
		Riddle riddle46 = new Riddle("	一个人在什么情况下，才处于真正的任人宰割的地步？ 	","	 手术台上	", "经典"	, "无");
		Riddle riddle47 = new Riddle("	公共汽车上，两个人正在热烈的交谈，可围观的人却一句话也听不到，这是因为什么？	","	 这是一对聋哑人	", "经典"	, "无");
		Riddle riddle48 = new Riddle("	為什么男人和女人会分手？ 	","	 因为男女有「别」	", "经典"	, "无");
		Riddle riddle49 = new Riddle("	最不能在光天化日下见人的是什么东西？ 	","	 胶卷	", "经典"	, "无");
		Riddle riddle50 = new Riddle("	一双鞋卖16元，一只鞋卖多少钱？ 	","	 不卖	", "经典"	, "无");
		Riddle riddle51 = new Riddle("	世界上最舒服的地方在哪里? 	","	 妈妈的肚子里	", "经典"	, "无");
		Riddle riddle52 = new Riddle("	大勇说他和学校的老师很熟，在学校里哪里都能进去，但小涵偏说他有一处地方永远也不能进去，是什么地方呢？ 	","	 女厕所	", "经典"	, "无");
		Riddle riddle53 = new Riddle("	什么表以一天慢24小时？ 	","	 停表	", "经典"	, "无");
		Riddle riddle54 = new Riddle("	电脑与人脑有什么不同？ 	","	 电脑可以搬家，而人脑不行.	", "经典"	, "无");
		Riddle riddle55 = new Riddle("	永远也写不好的字是什么字？ 	","	 坏字	", "经典"	, "无");
		Riddle riddle56 = new Riddle("	纸上写着某一份命令。但是，看懂此文字的人，却绝对不能宣读命令。那么，纸上写的是什么呢？ 	","	 级上写着，不要念出此文	", "经典"	, "无");
		Riddle riddle57 = new Riddle("	阿美在事业并没有什么成就，为什么也有女强人的外号？ 	","	 因为她常常强人所难	", "经典"	, "无");
		Riddle riddle58 = new Riddle("	有两个人同时来到了河边，都想过河，但却只有一条小船，而且小船只能载1个人，请问，他们能否都过河？ 	","	 能，因为他们分别在河的两边	", "经典"	, "无");
		Riddle riddle59 = new Riddle("	一位服装模特儿小姐，即使在平日也穿着未经发表的新款服饰，但她常常看到穿着和她完全相同服饰的人。这是为什么？ 	","	 因为她看到镜子中的自己	", "经典"	, "无");
		Riddle riddle60 = new Riddle("	一个人午后在太阳下走，却看不见自己的影子。为什么？ 	","	 阴雨天遮住了太阳	", "经典"	, "无");
		Riddle riddle61 = new Riddle("	有一个人舔冰棒，为什么越舔冰棒越大支 	","	 因为他在南极舔	", "经典"	, "无");
		Riddle riddle62 = new Riddle("	小呆骑在大牛身上，为什么大牛不吃草？ 	","	 大牛是人	", "经典"	, "无");
		Riddle riddle63 = new Riddle("	有个男人站在时速240公里的列车顶上，虽然他不是一个会飞墙走壁的超人，但是他仍然显得从容自如、毫不紧张，为什么？ 	","	 因为当时火车还没开动	", "经典"	, "无");
		Riddle riddle64 = new Riddle("	单兵甲偷用了单兵乙的牙刷，单兵乙有B型肝炎，为什么单兵甲却没有被传染？	","	 他拿去刷皮鞋了	", "经典"	, "无");
		Riddle riddle65 = new Riddle("	教堂向祖父办告解之前，都要先做那件事？ 	","	 犯罪	", "经典"	, "无");
		Riddle riddle66 = new Riddle("	某人买了易开罐农药，打算自杀，他的情人也要求同归与尽，但农药份量必须一整罐才会毙命，结果两个人都死了，为什么？ 	","	 打开农药罐已坏再拿一罐	", "经典"	, "无");
		Riddle riddle67 = new Riddle("	拿枪上侧所(地名)？ 	","	 保定	", "经典"	, "无");
		Riddle riddle68 = new Riddle("	冰到底是什么东西？ 	","	 一块一块的水	", "经典"	, "无");
		Riddle riddle69 = new Riddle("	有一棵树，在距树7米的地方有一堆草，一头牛用一根3米的绳子栓着，这头牛把这堆草全吃光了，为什么?(不考虑牛的体长) 	","	 牛没有拴在树上	", "经典"	, "无");
		Riddle riddle70 = new Riddle("	小明从外面买了好多东西回来，为什么她一进社区办公室就把手中的一捆布往地上一扔?	","	 拖布	", "经典"	, "无");
		Riddle riddle71 = new Riddle("	环球旅行。猜一现代香港名星名 	","	 周星驰	", "经典"	, "无");
		Riddle riddle72 = new Riddle("	保洁阿姨是什么人？ 	","	 女人	", "经典"	, "无");
		Riddle riddle73 = new Riddle("	给你一本杂志和一个火柴盒，你能使杂志只有三分之一放在桌边而不掉落下来吗?	","	 把杂志掀开三分之一放在桌边，自然就不会掉下来了	", "经典"	, "无");
		Riddle riddle74 = new Riddle("	最坚固的锁怕什么? 	","	 钥匙	", "经典"	, "无");
		Riddle riddle75 = new Riddle("	小陈半夜吃泡面，为什么一面吃，一面眼盯着表？ 	","	 那包面的食用期到今天	", "经典"	, "无");
		Riddle riddle76 = new Riddle("	上课偷看“脑筋急转弯”，如果被没收了，谁最高兴？ 	","	 老师的孩子	", "经典"	, "无");
		Riddle riddle77 = new Riddle("	法国人的笑声跟我们有什么不同？ 	","	 他们是用法语笑的	", "经典"	, "无");
		Riddle riddle78 = new Riddle("	什么票最危险? 	","	 绑票	", "经典"	, "无");
		Riddle riddle79 = new Riddle("	2木不成林！(打一字) 	","	 相	", "经典"	, "无");
		Riddle riddle80 = new Riddle("	想想看，如果外星人来到地球，他说的第一句话将会是什么？ 	","	 外星话	", "经典"	, "无");
		Riddle riddle81 = new Riddle("	为什么大象只有一只右耳朵？ 	","	 每只大象都有一只右耳朵	", "动物"	, "无");
		Riddle riddle82 = new Riddle("	猴子会说话，为什么？ 	","	 是他的外号码	", "动物"	, "无");
		Riddle riddle83 = new Riddle("	一个人在回家的路上碰到10只狮子，请问他会变成什么？ 	","	 十堆狮子大便	", "动物"	, "无");
		Riddle riddle84 = new Riddle("	猪为什么没完没了地吃？ 	","	 它想成为一只肉猪	", "动物"	, "无");
		Riddle riddle85 = new Riddle("	猴子每分钟能掰一个玉米，在果园里，一只猴子5分钟能掰几个玉米?	","	 没掰到一个	", "动物"	, "无");
		Riddle riddle86 = new Riddle("	猪皮是用来作什么的呢？ 	","	 包猪肉用的	", "动物"	, "无");
		Riddle riddle87 = new Riddle("	强尼每天晚上做梦都梦到猫要吃他，他又不是老鼠，为什么？	","	 他白天在迪尼斯扮演米老鼠	", "动物"	, "无");
		Riddle riddle88 = new Riddle("	什么“猴”不能吃？ 	","	 “火侯”	", "动物"	, "无");
		Riddle riddle89 = new Riddle("	如何防止被狗咬? 	","	 不要跑在狗的前面	", "动物"	, "无");
		Riddle riddle90 = new Riddle("	打狗看主人，打虎看什么？ 	","	 看你有没有种	", "动物"	, "无");
		Riddle riddle91 = new Riddle("	新兵阿国：“报告班长！我的豆浆里有一只苍蝇。”为什么班长却若无其事的告诉他放心喝，没有问题的？ 	","	 因为馒头里的蜘蛛会把苍蝇吃掉	", "动物"	, "无");
		Riddle riddle92 = new Riddle("	什么样的房子不能住人？？ 	","	 蜂房	", "动物"	, "无");
		Riddle riddle93 = new Riddle("	比细菌还小的东西是什么？ 	","	 细菌的儿子	", "动物"	, "无");
		Riddle riddle94 = new Riddle("	有一群小鸡在菜地里乱窜，小鸡是谁的？ 	","	 鸡妈妈的	", "动物"	, "无");
		Riddle riddle95 = new Riddle("	又一只狼经过，还是没有吃羊，再猜一海产品？ 	","	 虾（瞎）	", "动物"	, "无");
		Riddle riddle96 = new Riddle("	一只蚊子顺时钟绕着一个新买的而且是没有任何质量问题的高效捕蚊灯打转，但一直不会被吸进去，为什么呢? 	","	 因为捕蚊灯没有通电	", "动物"	, "无");
		Riddle riddle97 = new Riddle("	什么两个脑袋、六条腿、一条尾巴？ 	","	 人骑马	", "动物"	, "无");
		Riddle riddle98 = new Riddle("	有甲也有盔，有眼没有眉，无脚会赶路，有翅不会飞，这是什么？ 	","	 鱼	", "动物"	, "无");
		Riddle riddle99 = new Riddle("	谁是百兽之王？ 	","	 动物园的园长	", "动物"	, "无");
		Riddle riddle100 = new Riddle("	甲、乙两只狼狗举行1000米赛跑，假如两只狼狗同时跑到终点，那么哪只狼狗出汗多？	","	 狼狗不出汗	", "动物"	, "无");
		Riddle riddle101 = new Riddle("	恐龙为什么会灭亡？ 	","	 那个时候没有动物保护协会	", "动物"	, "无");
		Riddle riddle102 = new Riddle("	丽丽和小狗一起玩，突然，她看到小狗越来越小了。是什么原因呢？	","	 小狗离开小丽跑了，越跑越远	", "动物"	, "无");
		Riddle riddle103 = new Riddle("	养过电子鸡和电子狗的人，会有什么感受？ 	","	 鸡犬不宁	", "动物"	, "无");
		Riddle riddle104 = new Riddle("	世界上的猪都死光了。（打一歌名） 	","	 至少还有你	", "动物"	, "无");
		Riddle riddle105 = new Riddle("	把大象装进冰箱要几步？	","	 三步，先打开冰箱，再把大象放进去，最后把冰箱门关上。	", "动物"	, "无");
		Riddle riddle106 = new Riddle("	两个女人与一千只鸭子所说的话有何相似性呢？ 	","	 无稽(鸡)之谈	", "动物"	, "无");
		Riddle riddle107 = new Riddle("	龙的儿子与狗的儿子有什么差别？ 	","	 一为龙子一为犬	", "动物"	, "无");
		Riddle riddle108 = new Riddle("	为什么白鹭莺总是缩者一只脚睡觉？ 	","	 缩两只脚就会跌	", "动物"	, "无");
		Riddle riddle109 = new Riddle("	兔子为什么不吃窝边草？	","	 如果兔子吃了窝边草的话，那它的窝就没有可以隐藏的东西了	", "动物"	, "无");
		Riddle riddle110 = new Riddle("	为什么天上会有星星？ 	","	 证明爱因斯坦的相对论天上有星星地下也有猩猩	", "动物"	, "无");
		Riddle riddle111 = new Riddle("	一棵树绑着一只虎，绳长10公尺，距树公尺处有一堆草，要如何它才能吃到那堆草？	","	 老虎根本不吃草	", "动物"	, "无");
		Riddle riddle112 = new Riddle("	为什么母鸡的腿短？ 	","	 腿长了，生下的蛋会被子摔破	", "动物"	, "无");
		Riddle riddle113 = new Riddle("	动物园的大象死了，为什么大象管理员哭得那么伤心？	","	 他想到要挖那么大一个坑，所以就……	", "动物"	, "无");
		Riddle riddle114 = new Riddle("	猴子在树上摘菠萝，一分钟一个，十分钟摘多少个？ 	","	 菠萝不长在树上	", "动物"	, "无");
		Riddle riddle115 = new Riddle("	说它是牛不是牛，力小能背房子走。 	","	 蜗牛	", "动物"	, "无");
		Riddle riddle116 = new Riddle("	什么鱼不能吃？ 	","	 木鱼	", "动物"	, "无");
		Riddle riddle117 = new Riddle("	一头牛加一捆草等于什么？ 	","	 还是一头牛	", "动物"	, "无");
		Riddle riddle118 = new Riddle("	有一个婴儿喝了牛奶之后，一星期重了十公斤，为什么？ 	","	 那是一头牛	", "动物"	, "无");
		Riddle riddle119 = new Riddle("	有种动物，大小像只猫，长相又像虎，这是什么动物? 	","	 小老虎	", "动物"	, "无");
		Riddle riddle120 = new Riddle("	只有头却没有身体的牛，叫做什么牛？ 	","	 一头牛	", "动物"	, "无");
		Riddle riddle121 = new Riddle("	一个公鸡在尖尖的房子上下了一个蛋，它会往哪边掉呢? 	","	 公鸡是不会生蛋的	", "动物"	, "无");
		Riddle riddle122 = new Riddle("	哪儿的海不产鱼? 	","	 辞海	", "动物"	, "无");
		Riddle riddle123 = new Riddle("	鱼儿为什么不说话？ 	","	 因为他在水里	", "动物"	, "无");
		Riddle riddle124 = new Riddle("	渔夫最怕什么？ 	","	 没人吃鱼	", "动物"	, "无");
		Riddle riddle125 = new Riddle("	为什么一个人一天吃9头牛？ 	","	 吃的是蜗牛	", "动物"	, "无");
		Riddle riddle126 = new Riddle("	阿强和阿燕裸体死在一间密室中、現场只留下一滩水和一些碎玻璃，请推测他们的死因？	","	 阿强和阿燕是金鱼	", "动物"	, "无");
		Riddle riddle127 = new Riddle("	为什么蝙蝠会经常倒吊着？ 	","	 因为它胃下垂	", "动物"	, "无");
		Riddle riddle128 = new Riddle("	我常带着我的狗去晨跑，累得我和它都满头大汗，为什么？	","	 你见过狗满头大汗吗	", "动物"	, "无");
		Riddle riddle129 = new Riddle("	山岗上有三只狐狸，猎人开枪打死了一只，问山岗上还有几只狐狸？ 	","	 一只	", "动物"	, "无");
		Riddle riddle130 = new Riddle("	电线杆上三只麻雀正在打架，当中一只不小心掉下來，为什么其他两只也跟着掉下來？	","	 因为那两只拍手的时候掉了下来	", "动物"	, "无");
		Riddle riddle131 = new Riddle("	为什么熊冬眠时会睡这么久？ 	","	 没有人敢叫它起床	", "动物"	, "无");
		Riddle riddle132 = new Riddle("	米的爸爸是谁？ 	","	 米的爸爸是蝶，蝶恋花	", "动物"	, "无");
		Riddle riddle133 = new Riddle("	为什么小白看见100元和肉骨头他选肉骨头？ 	","	 小白是狗呀	", "动物"	, "无");
		Riddle riddle134 = new Riddle("	一头公牛加一头母牛，猜三个字？ 	","	 两头牛	", "动物"	, "无");
		Riddle riddle135 = new Riddle("	那一种蝙蝠不用休息？ 	","	 不修边幅（不休蝙蝠）	", "动物"	, "无");
		Riddle riddle136 = new Riddle("	饲养员将一串香蕉挂在竹竿上，要求大猩猩不搭凳子，不砍断竹枝拿下它。聪明的大猩猩想了想很快取到了香蕉。它是怎样拿到的？ 	","	 把竹竿放倒	", "动物"	, "无");
		Riddle riddle137 = new Riddle("	马的头朝南，马的尾朝哪？ 	","	 朝下	", "动物"	, "无");
		Riddle riddle138 = new Riddle("	一个老鼠洞里有五只老鼠，猫进洞吃了一只老鼠，洞里还剩下几只老鼠？ 	","	 没了	", "动物"	, "无");
		Riddle riddle139 = new Riddle("	大灰狼拖走了羊妈妈，小羊为什么也不声不响地跟了去？	","	 小羊在羊妈妈的肚子里	", "动物"	, "无");
		Riddle riddle140 = new Riddle("	5只鸡，5天生了5个蛋。100天内要100个蛋，需要多少只鸡？？ 	","	 依然是五只鸡.	", "动物"	, "无");
		Riddle riddle141 = new Riddle("	小明在图画课是交了一张全部涂黑的图画为什么老师还是算及格？	","	 因为小明画的是一个黑人在半夜里抓乌鸦	", "动物"	, "无");
		Riddle riddle142 = new Riddle("	乌龟为什么会突然「一个头两个大」？ 	","	 因为乌龟正在想这个问题	", "动物"	, "无");
		Riddle riddle143 = new Riddle("	一只蚂蚁从几百万米高的山峰落下来会怎么死？ 	","	 饿死	", "动物"	, "无");
		Riddle riddle144 = new Riddle("	为什么买一头牛只要一万元，而买三头牛却要五万元？ 	","	 三头牛当然比一头牛贵	", "动物"	, "无");
		Riddle riddle145 = new Riddle("	一只毛毛虫，过一条没桥的河，它怎么过去? 	","	 变成蝴蝶飞过去的	", "动物"	, "无");
		Riddle riddle146 = new Riddle("	谁的脚常年走路不穿鞋? 	","	 动物的脚	", "动物"	, "无");
		Riddle riddle147 = new Riddle("	一只已经饥饿以久的狼看见一只绵羊，却马上跑了，为什么？ 	","	 因为他跑去追羊	", "动物"	, "无");
		Riddle riddle148 = new Riddle("	为什么彤彤与壮壮第一次见面就一口咬定壮壮是喝羊奶长大的? 	","	 壮壮是一只羊	", "动物"	, "无");
		Riddle riddle149 = new Riddle("	“水蛇”“蟒蛇”“青竹蛇”哪一个比较长？ 	","	 “青竹蛇”三个字比较长	", "动物"	, "无");
		Riddle riddle150 = new Riddle("	苹果树上有一个苹果，一只小猴，请问树上有几个苹果，几只猴？	","	 一个苹果一只猴子也没有，因为去打架去了	", "动物"	, "无");
		Riddle riddle151 = new Riddle("	一只蜜蜂停在日历上，打一成语？ 	","	 风和日丽	", "动物"	, "无");
		Riddle riddle152 = new Riddle("	狐狸精最擅长迷惑男人，那么什么'精'男女一起迷? 	","	 酒精	", "动物"	, "无");
		Riddle riddle153 = new Riddle("	黑鸡厉害还是白鸡厉害?为什么? 	","	 黑鸡会生白蛋，白鸡不会生黑蛋	", "动物"	, "无");
		Riddle riddle154 = new Riddle("	蚊子咬在什么地方你不会觉得痒？ 	","	 别人身上	", "动物"	, "无");
		Riddle riddle155 = new Riddle("	何种动物最接近于人类? 	","	 寄生在人身体上的寄生虫	", "动物"	, "无");
		Riddle riddle156 = new Riddle("	树上有100只鸟，用什么方法才能把它们全部抓住？ 	","	 用照相机	", "动物"	, "无");
		Riddle riddle157 = new Riddle("	龟兔又赛跑了，这次兔子没有偷懒、贪玩但是这次兔子还是输了，为什么?	","	 乌龟把终点设在了海里	", "动物"	, "无");
		Riddle riddle158 = new Riddle("	怀孕的母狗怕人踢它，可是有个家伙踢它，它既不躲避也不生气，为什么？	","	 因为那家伙在他的肚子里踢	", "动物"	, "无");
		Riddle riddle159 = new Riddle("	世界上哪儿的大象最小? 	","	 书上的	", "动物"	, "无");
		Riddle riddle160 = new Riddle("	小涵捉到一只小鸟，她把小鸟放在桌子上，小鸟却没有飞，是什么原因？	","	 鸟已死	", "动物"	, "无");
		Riddle riddle161 = new Riddle("	为什么现代人越来越言而无信? 	","	 因为打电话比写信方便	", "冷笑话"	, "无");
		Riddle riddle162 = new Riddle("	根据调查，发现本国各地在同一时间，竟然有许多人说着相同英语的奇怪现象，这究竟是怎么一回事呢 	","	 原来他们都均同时收听英语广播讲座节目中的发音练习	", "冷笑话"	, "无");
		Riddle riddle163 = new Riddle("	有一天，有一班学生正在小考，有一个学生，他答出来之后，为什么老师还打了他一顿？	","	 因为他把答案念给同学听	", "冷笑话"	, "无");
		Riddle riddle164 = new Riddle("	什么事是林先生和林太太每天睡觉时都要做的事？ 	","	 闭上眼睛	", "冷笑话"	, "无");
		Riddle riddle165 = new Riddle("	爱斯基摩人用什么吃饭？ 	","	 用嘴吃饭	", "冷笑话"	, "无");
		Riddle riddle166 = new Riddle("	甲乙两位仇人以喝毒酒决定生死，为什么乙选了没毒的酒却死了？ 	","	 被甲打死了	", "冷笑话"	, "无");
		Riddle riddle167 = new Riddle("	债权和债务的最大区别是什么? 	","	 一个容易记住，一个最不容易记住	", "冷笑话"	, "无");
		Riddle riddle168 = new Riddle("	哪种比赛，赢的得不到奖品，输的却有奖品?	","	 划拳喝酒	", "冷笑话"	, "无");
		Riddle riddle169 = new Riddle("	金钟奖、金马奖、金像奖哪个对国家贡献最大？ 	","	 金钟奖(精忠报国)	", "冷笑话"	, "无");
		Riddle riddle170 = new Riddle("	为什么买一头牛只要一万元，而买三头牛却要五万元？ 	","	 三头牛当然比一头牛贵	", "冷笑话"	, "无");
		Riddle riddle171 = new Riddle("	不小心溺水时，若附近沒有其他人该如何自救？	","	 把水喝光，但是还是会胀死	", "冷笑话"	, "无");
		Riddle riddle172 = new Riddle("	晶晶洗澡时，每次都有从洗澡水里拿东西往嘴里塞的习惯，而且奇怪的是，她还不断称赞好吃。请问她在吃什么？ 	","	 澡和枣同音	", "冷笑话"	, "无");
		Riddle riddle173 = new Riddle("	麦克杰克逊为什么要去做漂白手术？ 	","	 怕遭到不白之冤	", "冷笑话"	, "无");
		Riddle riddle174 = new Riddle("	做什么事情最开心？ 	","	 开心手术	", "冷笑话"	, "无");
		Riddle riddle175 = new Riddle("	先有鸡还是先有蛋？ 	","	 先有蛋，因为在新华字典里面蛋在鸡的前面	", "冷笑话"	, "无");
		Riddle riddle176 = new Riddle("	华盛顿小时候砍倒他父亲的樱桃树时，他父亲为什么不马上处罚他？	","	 因为他手头上还有斧头	", "冷笑话"	, "无");
		Riddle riddle177 = new Riddle("	明明是个“错”字，为什么小华却偏偏说要“对”？ 	","	 的确是个错字呀	", "冷笑话"	, "无");
		Riddle riddle178 = new Riddle("	好与坏的中间是什么？	","	 与	", "冷笑话"	, "无");
		Riddle riddle179 = new Riddle("	小王开医院，生意一直不是很如意，一天他的医院突然车水马龙排了一大堆人，为什么？	","	 因为他在医院门口贴了今日住院3折	", "冷笑话"	, "无");
		Riddle riddle180 = new Riddle("	什么数字让女士又爱又恨？ 	","	 三八	", "冷笑话"	, "无");
		Riddle riddle181 = new Riddle("	我和你爸爸的弟弟的儿子的同学的哥哥是什么关系? 	","	 没关系	", "冷笑话"	, "无");
		Riddle riddle182 = new Riddle("	女人生小孩 	","	 血口喷人	", "冷笑话"	, "无");
		Riddle riddle183 = new Riddle("	如果诸葛亮活着，世界现在会有什么不同？ 	","	 会多一个人	", "冷笑话"	, "无");
		Riddle riddle184 = new Riddle("	一群惧内的大丈夫们正聚集在一起商量怎样重振男子汉的雄风，突然听说他们的老婆来了，大家四处逃窜，惟独一人没有跑，为什么？ 	","	 吓死了	", "冷笑话"	, "无");
		Riddle riddle185 = new Riddle("	波霸参加500公尺赛跑，一路领先的波霸不慎摔了一大跤却还能得第一名，为什么？	","	 因为其它人都被陷到坑里了	", "冷笑话"	, "无");
		Riddle riddle186 = new Riddle("	爱斯基摩人用什么吃饭？ 	","	 用嘴吃饭	", "冷笑话"	, "无");
		Riddle riddle187 = new Riddle("	一百个男人无法抬起的物体，却有一女子可单手举起，此物体究竟为何?	","	 一颗鸡蛋（仅仅一个鸡蛋，100个人没法抬）	", "冷笑话"	, "无");
		Riddle riddle188 = new Riddle("	外国人问路，小明拼命有英语对他说，他却一点也听不懂，这是为什么？	","	 因为他是法国人	", "冷笑话"	, "无");
		Riddle riddle189 = new Riddle("	小王是一名优秀士兵，一天他在站岗值勤时，明明看到有敌人悄悄向他摸过来，为什么他却睁一只眼闭一只眼？ 	","	 他正在瞄准	", "冷笑话"	, "无");
		Riddle riddle190 = new Riddle("	亚当和夏娃结婚后，最大的遗憾是什么？ 	","	 没有人来喝喜酒	", "冷笑话"	, "无");
		Riddle riddle191 = new Riddle("	老师要学生写关于牛奶的文章，要求写200字，为什么沙米尔只写了20个字？	","	 沙米写的是浓缩牛奶	", "冷笑话"	, "无");
		Riddle riddle192 = new Riddle("	超人和蝙蝠侠的最大区别是什么？	","	 蝙蝠侠把内裤穿在里面，超人把内裤穿在外面	", "冷笑话"	, "无");
		Riddle riddle193 = new Riddle("	两位帅哥因何为了一位长相如恐龙般的女子大打出手？ 	","	 打输的要娶她	", "冷笑话"	, "无");
		Riddle riddle194 = new Riddle("	卖火柴的小女孩如果投胎转世來到现代，最有可能变成什么？	","	 兼售打火机的槟榔西施	", "冷笑话"	, "无");
		Riddle riddle195 = new Riddle("	爸爸答应汉森，只要考试及格，就奖励10元钱，可为什么汉森还是不及格？	","	 为了给爸爸省钱	", "冷笑话"	, "无");
		Riddle riddle196 = new Riddle("	东东养的鸽子在明明家下了一个蛋，请问这个蛋应属于谁的？ 	","	 鸽子的	", "冷笑话"	, "无");
		Riddle riddle197 = new Riddle("	为什么养长颈鹿最不花钱？	","	 因为他们的脖子长，一点点食物都要走很长的路才能到肚子.	", "冷笑话"	, "无");
		Riddle riddle198 = new Riddle("	一个老老人头顶上只剩三根头发，有一天他要参加重要盛会，为什么他仍忍痛拔掉其中一根头发呢？ 	","	 因为他要梳中分	", "冷笑话"	, "无");
		Riddle riddle199 = new Riddle("	蚊子咬在什么地方你不会觉得痒？ 	","	 别人身上	", "冷笑话"	, "无");
		Riddle riddle200 = new Riddle("	小王开医院，生意一直不是很如意，一天他的医院突然车水马龙排了一大堆人，为什么？	","	 因为他在医院门口贴了今日住院3折	", "冷笑话"	, "无");
		Riddle riddle201 = new Riddle("	歹徒抢劫MTV店，朝店主开了一枪，店主情急之下抽出一卷影带挡，居然平安无事，为什么？ 	","	 歹徒拿得是水枪	", "冷笑话"	, "无");
		Riddle riddle202 = new Riddle("	小王住的是楼房，为什么每次出门还要上楼? 	","	 他住地下室	", "冷笑话"	, "无");
		Riddle riddle203 = new Riddle("	一只饿猫从一只胖老鼠身旁走过，为什么那只饥饿的老猫竟无动于衷继续走它的路，连看都没看这只老鼠。 	","	 这是一只可怜的瞎猫子碰到一只死耗子。	", "冷笑话"	, "无");
		Riddle riddle204 = new Riddle("	医生手术为何带口罩? 	","	 怕人认出来	", "冷笑话"	, "无");
		Riddle riddle205 = new Riddle("	为什么会有人见死不救？ 	","	 死都死了还救什么	", "冷笑话"	, "无");
		Riddle riddle206 = new Riddle("	一个胖子和一个瘦子一起跳楼，谁先到达地面？ 	","	 围观的群众	", "冷笑话"	, "无");
		Riddle riddle207 = new Riddle("	你每天做作业时先干什么？ 	","	 打开本子	", "冷笑话"	, "无");
		Riddle riddle208 = new Riddle("	你能做，我能做，大家都做；一个人能做，两个人不能一起做。这是做什么？	","	 做梦	", "冷笑话"	, "无");
		Riddle riddle209 = new Riddle("	什么时候是老二最爽的时候？ 	","	 当老大不在不能欺负老二时	", "冷笑话"	, "无");
		Riddle riddle210 = new Riddle("	姑妈送给小花一只小猫，这只小猫没有死掉，也没有跑掉，小花也没有把它送人，为什么三个月后姑妈来小花家在没有看见小猫？ 	","	 它已长成大猫了	", "冷笑话"	, "无");
		Riddle riddle211 = new Riddle("	动物园里，大象的鼻子最长，鼻子第二长的是什么？ 	","	 小象	", "冷笑话"	, "无");
		Riddle riddle212 = new Riddle("	阿丁做起事来总是拖泥带水，为什么却从没被长官处罚过？	","	 阿丁是盖碉堡的士兵	", "冷笑话"	, "无");
		Riddle riddle213 = new Riddle("	某岛上有只乌龟，正中央是棵椰子树，岛的旁边还有一座岛，乌龟想过去，但又不太会游水，请问它该怎么过？ 	","	 他还在想	", "冷笑话"	, "无");
		Riddle riddle214 = new Riddle("	怎么使麻雀安静下来？ 	","	 压它一下（鸦雀无声)	", "冷笑话"	, "无");
		Riddle riddle215 = new Riddle("	草本（打一化合物） 	","	 苯	", "冷笑话"	, "无");
		Riddle riddle216 = new Riddle("	把什么打破了不会受到处分而会得到奖励? 	","	 记录	", "冷笑话"	, "无");
		Riddle riddle217 = new Riddle("	阿三死了，为什么大毛理直气壮的说：“凶手不是我，绝对另有其人！”	","	 因为阿三是电视推理剧场中的	", "冷笑话"	, "无");
		Riddle riddle218 = new Riddle("	老鹰的绝症是什么? 	","	 恐高症	", "冷笑话"	, "无");
		Riddle riddle219 = new Riddle("	大多数人是用左手端碗，右手吃饭，对吧？ 	","	 那要嘴巴干什么	", "冷笑话"	, "无");
		Riddle riddle220 = new Riddle("	嫦娥为什么后悔上广寒宫？ 	","	 因为月亮上没有赛月饼	", "冷笑话"	, "无");
		Riddle riddle221 = new Riddle("	为什么自由女神像老站在纽约港？ 	","	 因为她坐不下去	", "冷笑话"	, "无");
		Riddle riddle222 = new Riddle("	请问你，甚么狗不会叫？ 	","	 热狗	", "冷笑话"	, "无");
		Riddle riddle223 = new Riddle("	不小心溺水时，若附近沒有其他人该如何自救？	","	 把水喝光，但是还是会胀死	", "冷笑话"	, "无");
		Riddle riddle224 = new Riddle("	“只”字加一笔，变成什么字？	","	 冲（先把“只”立起来）	", "冷笑话"	, "无");
		Riddle riddle225 = new Riddle("	鸭蛋一打有多少个？ 	","	 全没有了碎了	", "冷笑话"	, "无");
		Riddle riddle226 = new Riddle("	小明点了一份全熟的牛排，但是为什么一切下去居然流出血来？	","	 因为不小心切到手了	", "冷笑话"	, "无");
		Riddle riddle227 = new Riddle("	亮亮的生日在三月三十日，请问是哪年的三月三十日? 	","	 每年的三月三十日	", "冷笑话"	, "无");
		Riddle riddle228 = new Riddle("	林老生大手术后换了一个人工心脏。病好了后，她的女友却马上提出分手，为什么会这样?	","	 没有真心爱她	", "冷笑话"	, "无");
		Riddle riddle229 = new Riddle("	小明上班时间吃了红豆汤圆，经理看见后生气的说，太闲了是不是，小明回答了一句什么话把经理气的差点晕倒? 	","	 不，是甜的	", "冷笑话"	, "无");
		Riddle riddle230 = new Riddle("	小朋友在游泳池游泳，游了一阵，大勇数了数，发觉少了一个，忙向老师报告，老师却说没有少，是什么原因呢？ 	","	 大勇忘了数上自己	", "冷笑话"	, "无");
		Riddle riddle231 = new Riddle("	武士刀和日本人有什么关系？ 	","	 他们是剖腹之交	", "冷笑话"	, "无");
		Riddle riddle232 = new Riddle("	先有鸡还是先有蛋？ 	","	 先有蛋，因为在新华字典里面蛋在鸡的前面	", "冷笑话"	, "无");
		Riddle riddle233 = new Riddle("	陈先生走在路上，眼前有一张千元大钞，他明明看见了，为什么不去捡？	","	 那张千元大钞票拿在别人手里	", "冷笑话"	, "无");
		Riddle riddle234 = new Riddle("	大家都不想得到的是什么？ 	","	 得病	", "冷笑话"	, "无");
		Riddle riddle235 = new Riddle("	醉鬼是什么人？ 	","	 宣布自己没醉的人	", "冷笑话"	, "无");
		Riddle riddle236 = new Riddle("	哪一种竹子不长在土里？ 	","	 爆竹	", "冷笑话"	, "无");
		Riddle riddle237 = new Riddle("	象皮、老虎皮、狮子皮，哪一个比较差？ 	","	 象皮(橡皮擦)	", "冷笑话"	, "无");
		Riddle riddle238 = new Riddle("	比细菌还小的东西是什么？ 	","	 细菌的儿子	", "冷笑话"	, "无");
		Riddle riddle239 = new Riddle("	小明的爸爸是警察，他眼看着儿子偷了一样东西，却没有多加管教，这是怎么回事？	","	 儿子在偷笑呀	", "冷笑话"	, "无");
		Riddle riddle240 = new Riddle("	什么蛋又能走又能跳还会说话？ 	","	 笨蛋	", "冷笑话"	, "无");
		Riddle riddle241 = new Riddle("	离婚的主要起因是什么？ 	","	 结婚	", "搞笑"	, "无");
		Riddle riddle242 = new Riddle("	排着对上厕所，打一地名？ 	","	 伦敦	", "搞笑"	, "无");
		Riddle riddle243 = new Riddle("	有人说，女人象一本书，那么胖女人象什么书？ 	","	 合订本	", "搞笑"	, "无");
		Riddle riddle244 = new Riddle("	老王的头发已经掉光了，可为什么他还老去理发店? 	","	 老王是理发师	", "搞笑"	, "无");
		Riddle riddle245 = new Riddle("	妈妈叫小民去拿碟子来装菜，小民拿来了，却被骂了一顿，为什么？	","	 他拿的是光喋	", "搞笑"	, "无");
		Riddle riddle246 = new Riddle("	自己的缺点令自己讨厌是在什么时候？ 	","	 在别人身上看到时	", "搞笑"	, "无");
		Riddle riddle247 = new Riddle("	阿贵歪点子特别多。一次，他将一根小棍子放在地上，却使任何人都无法跨过去，阿贵是怎样放的？ 	","	 将小棍子放到墙边	", "搞笑"	, "无");
		Riddle riddle248 = new Riddle("	包公的脸为什么是黑的？ 	","	 因为额头上有个月亮月亮都是晚上出来	", "搞笑"	, "无");
		Riddle riddle249 = new Riddle("	孔子和孟子有什么不同？ 	","	 孔子把儿子牵在身边，而孟子把儿子放在头上	", "搞笑"	, "无");
		Riddle riddle250 = new Riddle("	青蛙为什么能跳得比树高? 	","	 树不会跳	", "搞笑"	, "无");
		Riddle riddle251 = new Riddle("	到家了，我为什么不进去? 	","	 忘了带钥匙	", "搞笑"	, "无");
		Riddle riddle252 = new Riddle("	一个不识字的人捂住识字的人的耳朵，让他读自己老婆的来信。他为什么要这样做？	","	 怕识字的人听到老婆说什么	", "搞笑"	, "无");
		Riddle riddle253 = new Riddle("	从前有只鸡，鸡的左面有只猫，右面有条狗，前面有只兔子，鸡的后面是什么？	","	 注意第一句话，从的前面有只鸡，那么鸡的后面当然是“从”了	", "搞笑"	, "无");
		Riddle riddle254 = new Riddle("	狼来了	","	 杨桃	", "搞笑"	, "无");
		Riddle riddle255 = new Riddle("	打狗看主人，打虎看什么？ 	","	 看你有没有种	", "搞笑"	, "无");
		Riddle riddle256 = new Riddle("	单兵甲偷用了单兵乙的牙刷，单兵乙有B型肝炎，为什么单兵甲却没有被传染？	","	 他拿去刷皮鞋了	", "搞笑"	, "无");
		Riddle riddle257 = new Riddle("	老张二十多年一直卖假货，为什么大家却认为他是大好人？ 	","	 老张卖的是假发	", "搞笑"	, "无");
		Riddle riddle258 = new Riddle("	阿忠结婚好几年了，却没生下一个孩子，这是为什么？ 	","	 他生的是双胞胎	", "搞笑"	, "无");
		Riddle riddle259 = new Riddle("	马要如何过河？ 	","	 走日字步	", "搞笑"	, "无");
		Riddle riddle260 = new Riddle("	小花站起来同饭桌一样高，两年之后，反而能在桌子下活动自如，为什么？	","	 小花是一条狗	", "搞笑"	, "无");
		Riddle riddle261 = new Riddle("	除了玻璃、瓷器等容易碎的东西要小心轻放外，还有什么东西要小心轻放？ 	","	 屁	", "搞笑"	, "无");
		Riddle riddle262 = new Riddle("	厕所里应该摆什么花？ 	","	 五月花	", "搞笑"	, "无");
		Riddle riddle263 = new Riddle("	老师说我们的身体里有106块骨头，可是，小明说他身体里有107块骨头，这是为什么？	","	 因为小明不小心吃下一块鱼骨头。	", "搞笑"	, "无");
		Riddle riddle264 = new Riddle("	拆信。（打一城市名）？ 	","	 开封	", "搞笑"	, "无");
		Riddle riddle265 = new Riddle("	连续剧西游记中，谁最历害又聪明？ 	","	 编剧	", "搞笑"	, "无");
		Riddle riddle266 = new Riddle("	如果你生出的孩子只有一只右手你会怎么办? 	","	 废话，哪有人有两只右手的。	", "搞笑"	, "无");
		Riddle riddle267 = new Riddle("	公共汽车上，两个人正在热烈的交谈，可围观的人却一句话也听不到，这是因为什么？	","	 这是一对聋哑人	", "搞笑"	, "无");
		Riddle riddle268 = new Riddle("	下雪天，阿文开了暖气，关上门窗，为什么还感到很冷？ 	","	 他在屋外	", "搞笑"	, "无");
		Riddle riddle269 = new Riddle("	经理不会做饭，可有一道菜特别拿手，是什么？ 	","	 炒鱿鱼	", "搞笑"	, "无");
		Riddle riddle270 = new Riddle("	阿珠结婚后，为什么宁愿睡地板也不肯跟丈夫睡水床? 	","	 她有晕船的毛病	", "搞笑"	, "无");
		Riddle riddle271 = new Riddle("	阿火在营光日的考试全部答对，为什么却没得到满分？ 	","	 因为考的是是非题	", "搞笑"	, "无");
		Riddle riddle272 = new Riddle("	歌仔戏和歌剧有什么不一样？	","	 其实是一样的一个是传统歌仔戏，一个是西方歌仔戏	", "搞笑"	, "无");
		Riddle riddle273 = new Riddle("	江家有三个女儿，大女儿、二女儿、三女儿。谁的身材最辣？	","	 大女儿因为姜还是老的辣	", "搞笑"	, "无");
		Riddle riddle274 = new Riddle("	的士生意不好，打一韩国明星? 	","	 车太贤	", "搞笑"	, "无");
		Riddle riddle275 = new Riddle("	龙的儿子与狗的儿子有什么差别？ 	","	 一为龙子一为犬	", "搞笑"	, "无");
		Riddle riddle276 = new Riddle("	小明上班时间吃了红豆汤圆，经理看见后生气的说，太闲了是不是，小明回答了一句什么话把经理气的差点晕倒? 	","	 不，是甜的	", "搞笑"	, "无");
		Riddle riddle277 = new Riddle("	当今社会，个体户大都靠什么吃饭？ 	","	 嘴	", "搞笑"	, "无");
		Riddle riddle278 = new Riddle("	聪明人比一般人多了个什么？ 	","	 心眼	", "搞笑"	, "无");
		Riddle riddle279 = new Riddle("	如果苹果没落在牛顿头顶上，会落到哪里？ 	","	 地上	", "搞笑"	, "无");
		Riddle riddle280 = new Riddle("	办什么事睁一只眼闭一只眼比较好些? 	","	 射击的时候	", "搞笑"	, "无");
		Riddle riddle281 = new Riddle("	吃苹果时，咬了一口发现有一条虫子，觉得特别恶心；看到两条虫子，觉得更恶心；请问：看到几条虫子让人最恶心？ 	","	 半条虫子	", "搞笑"	, "无");
		Riddle riddle282 = new Riddle("	小刚从5000米高的飞机上跳伞，过了两个小时才落到地面，为什么？	","	 他挂在了树上	", "搞笑"	, "无");
		Riddle riddle283 = new Riddle("	空调从楼上掉下来会变成啥？ 	","	 凶器废铁	", "搞笑"	, "无");
		Riddle riddle284 = new Riddle("	你能做，我能做，大家都做；一个人能做，两个人不能一起做。这是做什么？	","	 做梦	", "搞笑"	, "无");
		Riddle riddle285 = new Riddle("	我常带着我的狗去晨跑，累得我和它都满头大汗，为什么？	","	 你见过狗满头大汗吗	", "搞笑"	, "无");
		Riddle riddle286 = new Riddle("	一朵插在牛粪上的鲜花是什么花？ 	","	 牵牛花	", "搞笑"	, "无");
		Riddle riddle287 = new Riddle("	地球没有水时像什么? 	","	 核桃	", "搞笑"	, "无");
		Riddle riddle288 = new Riddle("	曹孟德赤壁惨败。（打二歌星） 	","	 孙悦、刘欢	", "搞笑"	, "无");
		Riddle riddle289 = new Riddle("	敲凳子会发出“咚咚”声，那么凳子敲人会发出什么声？ 	","	 惨叫声	", "搞笑"	, "无");
		Riddle riddle290 = new Riddle("	蚂蚁、蜜蜂和蜈蚣，哪一种昆虫最不贪钱？ 	","	 蜈蚣(因为无功不受禄)	", "搞笑"	, "无");
		Riddle riddle291 = new Riddle("	大气的流动叫“气流”；河水的流动叫“水流”；那风的流动呢？ 	","	 风流	", "搞笑"	, "无");
		Riddle riddle292 = new Riddle("	为什么熊冬眠时会睡这么久？ 	","	 没有人敢叫它起床	", "搞笑"	, "无");
		Riddle riddle293 = new Riddle("	阿强和阿燕裸体死在一间密室中、現场只留下一滩水和一些碎玻璃，请推测他们的死因？	","	 阿强和阿燕是金鱼	", "搞笑"	, "无");
		Riddle riddle294 = new Riddle("	避孕套---- 打一地名 	","	 包头	", "搞笑"	, "无");
		Riddle riddle295 = new Riddle("	请解释擒贼先擒王。 	","	 丢了东西先驱找姓王的	", "搞笑"	, "无");
		Riddle riddle296 = new Riddle("	阿研的口袋里共有10个硬币，漏掉了10个硬币，口袋里还有什么？ 	","	 一个破洞	", "搞笑"	, "无");
		Riddle riddle297 = new Riddle("	上课的时候，同学们都坐着上课，但是小李上每一节课都站着。为什么？	","	 小李是老师	", "搞笑"	, "无");
		Riddle riddle298 = new Riddle("	战场上，子弹最密集的地方在哪里？ 	","	 在弹药运输车上	", "搞笑"	, "无");
		Riddle riddle299 = new Riddle("	「双手万能」这句话，什么时候会凸槌？ 	","	 踢球的时候	", "搞笑"	, "无");
		Riddle riddle300 = new Riddle("	八点钟和九点钟有什么不一样？ 	","	 差一点	", "搞笑"	, "无");
		Riddle riddle301 = new Riddle("	既没下雨也没出太阳，某先生为什么要撑伞？ 	","	 他是神经病	", "搞笑"	, "无");
		Riddle riddle302 = new Riddle("	六岁的小明总是喜欢把家里的闹钟整坏，妈妈为什么总是让不会修理钟表的爸爸代为修理?	","	 妈妈让爸爸修理小明	", "搞笑"	, "无");
		Riddle riddle303 = new Riddle("	为什么吃完晚餐后，全家都喜欢坐在电视机前看电视？ 	","	 因为站久了脚会酸	", "搞笑"	, "无");
		Riddle riddle304 = new Riddle("	贝多芬给了我们什么样的启示？ 	","	 背了就会多分	", "搞笑"	, "无");
		Riddle riddle305 = new Riddle("	动物园的大象死了，为什么大象管理员哭得那么伤心？	","	 他想到要挖那么大一个坑，所以就……	", "搞笑"	, "无");
		Riddle riddle306 = new Riddle("	为什么刘备三顾茅庐，诸葛亮才肯见他？ 	","	 因为前两次没带礼	", "搞笑"	, "无");
		Riddle riddle307 = new Riddle("	有一个人发高烧50度，他这时该找谁帮忙？ 	","	 消防队	", "搞笑"	, "无");
		Riddle riddle308 = new Riddle("	考试时，阿财一題都不会写，但是为什么突然眼睛一亮，开始振笔疾书？	","	 他在写班級、座号、姓名。	", "搞笑"	, "无");
		Riddle riddle309 = new Riddle("	小李昨天在客户面前骂总经理是笨蛋，结果小李被开除了，为什么？	","	 因为小李泄露了公司的最高机密	", "搞笑"	, "无");
		Riddle riddle310 = new Riddle("	有只小北极熊早上醒来后一直追问熊妈妈，他是不是一只小浣熊，他妈妈回答：“你当然是北极熊”，可是他为什么还是不相信？ 	","	 因为他觉得很冷	", "搞笑"	, "无");
		Riddle riddle311 = new Riddle("	老李带婴儿去喝酒，居然还让婴儿喝了三大杯啤酒，旁边的人为什么都不劝阻或责骂？	","	 婴儿是那个人的外号	", "搞笑"	, "无");
		Riddle riddle312 = new Riddle("	三更半夜回家才发现忘记带钥匙，家里又没有其他人在，这时你最大的愿望是什么?	","	 门忘锁了	", "搞笑"	, "无");
		Riddle riddle313 = new Riddle("	男人泡澡堂-----打一军事用品。 	","	 炮弹	", "搞笑"	, "无");
		Riddle riddle314 = new Riddle("	为什么军中的早餐一直是豆浆馒头，从不吃稀饭？ 	","	 馒头比较好数	", "搞笑"	, "无");
		Riddle riddle315 = new Riddle("	理发师最不喜欢的人是谁？ 	","	 秃头的人	", "搞笑"	, "无");
		Riddle riddle316 = new Riddle("	为什么夏天才有台风？ 	","	 因为台风要冬眠	", "搞笑"	, "无");
		Riddle riddle317 = new Riddle("	农夫养了10头牛，为什么只有19只角？	","	 因为一只是犀牛	", "搞笑"	, "无");
		Riddle riddle318 = new Riddle("	如果说儿童是国家未来的栋梁，那么儿童肚子里的蛔虫是什么？	","	 当然栋梁的蛀虫了	", "搞笑"	, "无");
		Riddle riddle319 = new Riddle("	传说中遇见白无常者“活”，遇见黑无常者“死”，那么同时遇见黑白无常呢？	","	 吓得半死不活	", "搞笑"	, "无");
		Riddle riddle320 = new Riddle("	胖姐阿英站上人体秤时，为何指针却只指着5？ 	","	 指针已转过一圈了	", "搞笑"	, "无");
		Riddle riddle321 = new Riddle("	期终考试成绩下来了，平平的四门功课全是零分。老师却说比起某些同学来平平有一条是值得表扬的。老师指的是什么？ 	","	 平平没有作弊	", "儿童"	, "无");
		Riddle riddle322 = new Riddle("	英国出生过大人物吗？ 	","	 没有，全是婴儿	", "儿童"	, "无");
		Riddle riddle323 = new Riddle("	三个孩子吃三个饼要用3分钟，九十个孩子九十个饼要用多少时间?	","	 也是三分钟，九十个孩子同时吃	", "儿童"	, "无");
		Riddle riddle324 = new Riddle("	法王路易十四被砍头后他的儿子当了什么？ 	","	 孤儿	", "儿童"	, "无");
		Riddle riddle325 = new Riddle("	一个最贪玩的小孩最喜欢什么课? 	","	 下课	", "儿童"	, "无");
		Riddle riddle326 = new Riddle("	小朋友在游泳池游泳，游了一阵，大勇数了数，发觉少了一个，忙向老师报告，老师却说没有少，是什么原因呢？ 	","	 大勇忘了数上自己	", "儿童"	, "无");
		Riddle riddle327 = new Riddle("	小陈半夜吃泡面，为什么一面吃，一面眼盯着表？ 	","	 那包面的食用期到今天	", "儿童"	, "无");
		Riddle riddle328 = new Riddle("	北京王府井步行街上来往最多的是什么人？ 	","	 行人	", "儿童"	, "无");
		Riddle riddle329 = new Riddle("	有一天，有一班学生正在小考，有一个学生，他答出来之后，为什么老师还打了他一顿？	","	 因为他把答案念给同学听	", "儿童"	, "无");
		Riddle riddle330 = new Riddle("	一架高空飞行的客机在航行中，小王突然打开门冲出去，为什么他没摔死?	","	 他是冲进了厕所	", "儿童"	, "无");
		Riddle riddle331 = new Riddle("	一对健康夫妇，为什么生出只有一只右眼的婴儿？ 	","	 每个人都只有一只右眼	", "儿童"	, "无");
		Riddle riddle332 = new Riddle("	不管长得多像的双胞胎，都会有人分得出来，这人是谁?	","	 他们自己	", "儿童"	, "无");
		Riddle riddle333 = new Riddle("	贝儿的妈妈从外地买回一种鱼，无论放多长时间也不会臭。为什么？ 	","	 木鱼	", "儿童"	, "无");
		Riddle riddle334 = new Riddle("	小红和小丽是同学，也住在同一条街，她们总是一起上学，可是每天一出家门就一个向左走，一个向右走，这是怎么回事呢？ 	","	 他们的家门是相对着的	", "儿童"	, "无");
		Riddle riddle335 = new Riddle("	戴维一家五口外出旅游，说好一人带一瓶饮料可戴维坚持只带4瓶可口可乐，为什么？	","	 还有一瓶是汽水	", "儿童"	, "无");
		Riddle riddle336 = new Riddle("	老师说蚯蚓切成两段仍能再生，小东照老师话去做，蚯蚓却死了，为什么?	","	 小东是竖着将蚯蚓切开的	", "儿童"	, "无");
		Riddle riddle337 = new Riddle("	哪种人希望孩子越多越好？ 	","	 儿童用品制造商	", "儿童"	, "无");
		Riddle riddle338 = new Riddle("	小杰最爱吹牛，但是为什么他说大家都说他讲话很实在？ 	","	 那是他自己说的	", "儿童"	, "无");
		Riddle riddle339 = new Riddle("	有个刚生下的婴儿，有两个小孩和他是同年同月同日生的，而且是同一对父母生的，但他们不是双胞胎，这可能吗？ 	","	 三胞胎	", "儿童"	, "无");
		Riddle riddle340 = new Riddle("	为什么爷爷送给小明一份生日礼物，小明却一脚把礼物踢开？ 	","	 礼物是足球	", "儿童"	, "无");
		Riddle riddle341 = new Riddle("	冰变成水最快的方法是什么？ 	","	 去掉两点水	", "儿童"	, "无");
		Riddle riddle342 = new Riddle("	白冰冰与关公生的双胞胎叫什么名字？ 	","	 粉红派对	", "儿童"	, "无");
		Riddle riddle343 = new Riddle("	小杰在教室外捡到一只皮夹，为什么不交到老师那里？ 	","	 是自己的	", "儿童"	, "无");
		Riddle riddle344 = new Riddle("	沙沙声称自己是辨别母鸡年龄的专家，其绝招是用牙齿，为什么？	","	 把鸡亲口吃了来辨别母鸡的老嫩	", "儿童"	, "无");
		Riddle riddle345 = new Riddle("	篮子里的7个莱果掉了4个在桌子上，还有一个不知掉到哪去了，飞飞把桌子上的莱果拾进篮子里，又吃了一个，请问篮子里还剩下几个苹果？ 	","	 还有五个	", "儿童"	, "无");
		Riddle riddle346 = new Riddle("	小明吃麻辣面，加了胡椒又加辣椒，你猜他还会加什么东西？ 	","	 鼻涕和眼泪	", "儿童"	, "无");
		Riddle riddle347 = new Riddle("	阿辉从来不念书。为何也能成为全校的模范生？ 	","	 他是聋哑生	", "儿童"	, "无");
		Riddle riddle348 = new Riddle("	亮亮的生日在三月三十日，请问是哪年的三月三十日? 	","	 每年的三月三十日	", "儿童"	, "无");
		Riddle riddle349 = new Riddle("	几个孩子在分一些糖果，分来分去不平均。如果每个人得3粒，还剩7粒；如果每个人得5粒，又少了3粒。请问一共有几个孩子？几粒糖？ 	","	 5孩子，22颗糖果	", "儿童"	, "无");
		Riddle riddle350 = new Riddle("	小明点了一份全熟的牛排，但是为什么一切下去居然流出血来？	","	 因为不小心切到手了	", "儿童"	, "无");
		Riddle riddle351 = new Riddle("	爸爸什么时候像个孩子？ 	","	 在爷爷面前	", "儿童"	, "无");
		Riddle riddle352 = new Riddle("	小明次次都拿第一，为什么爸爸还要骂他啊? 	","	 倒数第一	", "儿童"	, "无");
		Riddle riddle353 = new Riddle("	爸爸丢了一样东西，为什么妈妈还特别高兴？ 	","	 他丢掉了坏习惯	", "儿童"	, "无");
		Riddle riddle354 = new Riddle("	萨维在电影院看电影时，为什么每次看的都是不连贯的电影？	","	 每次都是看一会儿睡一会儿	", "儿童"	, "无");
		Riddle riddle355 = new Riddle("	红和绿豆放在一个碟子里，小王为什么一下就把它们分开了?	","	 红豆和绿豆一样只有一颗	", "儿童"	, "无");
		Riddle riddle356 = new Riddle("	冬天，宝宝怕冷，到了屋里也不肯脱帽。可是他见了一个人乖乖地脱下帽，那人是谁？	","	 理发师	", "儿童"	, "无");
		Riddle riddle357 = new Riddle("	小红和妈妈都在一年级，为什么？ 	","	 妈妈是老师	", "儿童"	, "无");
		Riddle riddle358 = new Riddle("	老李带婴儿去喝酒，居然还让婴儿喝了三大杯啤酒，旁边的人为什么都不劝阻或责骂？	","	 婴儿是那个人的外号	", "儿童"	, "无");
		Riddle riddle359 = new Riddle("	考试时，小光全部都抄小明的，为什么小明得到一百分，小光却零分呢？	","	 因为小光连名字都抄小明的	", "儿童"	, "无");
		Riddle riddle360 = new Riddle("	班长告诉菜鸟，当拉开手榴弹的保险之后，口中先数五秒再投掷出去，菜鸟一切都按班长指示动作，但仍被炸死了，为什么？ 	","	 因为菜鸟有口吃	", "儿童"	, "无");
		Riddle riddle361 = new Riddle("	为什么小白看见100元和肉骨头他选肉骨头？ 	","	 小白是狗呀	", "儿童"	, "无");
		Riddle riddle362 = new Riddle("	如果说儿童是国家未来的栋梁，那么儿童肚子里的蛔虫是什么？	","	 当然栋梁的蛀虫了	", "儿童"	, "无");
		Riddle riddle363 = new Riddle("	老师用篮子拿来了五个苹果，准备分给五个小朋友，每个小朋友分一个，但是篮子里还要留一个，请问怎么分？ 	","	 五个人分一个，分四次	", "儿童"	, "无");
		Riddle riddle364 = new Riddle("	大龙家今晚的电视为什么只有图像，没有声音？ 	","	 上演的是哑剧	", "儿童"	, "无");
		Riddle riddle365 = new Riddle("	小明家住在五楼，可是电梯坏了，他自己也没有走楼梯，他却上了五楼回到家里，这可能吗？ 	","	 他妈妈背着他上楼	", "儿童"	, "无");
		Riddle riddle366 = new Riddle("	妈妈明明在叫大宝，但出来的竟是小宝，为什么？ 	","	 大宝不在	", "儿童"	, "无");
		Riddle riddle367 = new Riddle("	华盛顿小时候砍倒他父亲的樱桃树时，他父亲为什么不马上处罚他？	","	 因为他手头上还有斧头	", "儿童"	, "无");
		Riddle riddle368 = new Riddle("	东东养的鸽子在明明家下了一个蛋，请问这个蛋应属于谁的？ 	","	 鸽子的	", "儿童"	, "无");
		Riddle riddle369 = new Riddle("	小明去参加讲笑话比赛，一路上小明一直用冰块敷嘴巴，为什么？	","	 怕笑话到时候不新鲜	", "儿童"	, "无");
		Riddle riddle370 = new Riddle("	几个学生排队上校车。4个学生的前面有4个学生，4个学生的后面有4个学生，4个学生的中间也有4个学生。请问一共有几个学生？ 	","	 8个	", "儿童"	, "无");
		Riddle riddle371 = new Riddle("	我和你爸爸的弟弟的儿子的同学的哥哥是什么关系? 	","	 没关系	", "儿童"	, "无");
		Riddle riddle372 = new Riddle("	老师出了一道作文，题目是“假如我是个董事长”，同学都用心在写，为什么小强不动手？	","	 他在等秘书替他写	", "儿童"	, "无");
		Riddle riddle373 = new Riddle("	阿昌认识了一个女孩子，对她一见钟情，得知她没有男朋友，为什么还是闷闷不乐？	","	 女孩结婚了	", "儿童"	, "无");
		Riddle riddle374 = new Riddle("	大勇总爱吹牛，他说他能不用任何容器将一杯水带走，小朋友都不相信，但他却做到了，是怎么回事呢？ 	","	 将杯子倒扣在装满水的盆子里	", "儿童"	, "无");
		Riddle riddle375 = new Riddle("	大勇向小伙伴们吹嘘说：今天上课的时候，老师提了一个问题，全班除了他没有一个答对，你猜老师问的是什么问题？ 	","	 说:大勇你为什么又迟到了?	", "儿童"	, "无");
		Riddle riddle376 = new Riddle("	参加联考时，除了准考证之外，最重要的是什么？ 	","	 记得起床	", "儿童"	, "无");
		Riddle riddle377 = new Riddle("	小红口袋里原有10个铜钱，但它们都掉了，请问小红口袋里还剩下什么?	","	 还剩下一个洞	", "儿童"	, "无");
		Riddle riddle378 = new Riddle("	爱吃零食的小王体重最重时有50公斤，但最轻时只有3公斤，为什么？	","	 他刚出生的体重	", "儿童"	, "无");
		Riddle riddle379 = new Riddle("	灰姑娘的老爸老妈可能是谁？ 	","	 白雪公主与包公	", "儿童"	, "无");
		Riddle riddle380 = new Riddle("	哥哥吹嘘自己有非凡的记忆力，可有一件事他常忘，那是什么事？ 	","	 还弟弟的钱	", "儿童"	, "无");
		Riddle riddle381 = new Riddle("	米奇吃下了药，但忘了把药摇匀，达不到最佳效果，他该如何补救？	","	 不停地翻跟头	", "儿童"	, "无");
		Riddle riddle382 = new Riddle("	小平平时嘴闭不住，为什么现在一声不吭? 	","	 小平睡着了	", "儿童"	, "无");
		Riddle riddle383 = new Riddle("	冬冬的爸爸牙齿非常好，可是他经常去口腔医院，为什么? 	","	 因为他是牙科医生	", "儿童"	, "无");
		Riddle riddle384 = new Riddle("	阿强和阿燕裸体死在一间密室中、現场只留下一滩水和一些碎玻璃，请推测他们的死因？	","	 阿强和阿燕是金鱼	", "儿童"	, "无");
		Riddle riddle385 = new Riddle("	考试做判断题，小花掷骰子决定答案，但题目有20题，为什么他却扔了40次？	","	 他要验证一遍	", "儿童"	, "无");
		Riddle riddle386 = new Riddle("	你爸爸和你妈妈生了个儿子，他既不是你哥哥又不是你弟弟，他是谁？	","	 是你自己呀。	", "儿童"	, "无");
		Riddle riddle387 = new Riddle("	老师要学生写关于牛奶的文章，要求写200字，为什么沙米尔只写了20个字？	","	 沙米写的是浓缩牛奶	", "儿童"	, "无");
		Riddle riddle388 = new Riddle("	小涵捉到一只小鸟，她把小鸟放在桌子上，小鸟却没有飞，是什么原因？	","	 鸟已死	", "儿童"	, "无");
		Riddle riddle389 = new Riddle("	阿丁做起事来总是拖泥带水，为什么却从没被长官处罚过？	","	 阿丁是盖碉堡的士兵	", "儿童"	, "无");
		Riddle riddle390 = new Riddle("	阿姆斯壮登陆月球，他说的第一句话是什么？ 	","	 美式英语	", "儿童"	, "无");
		Riddle riddle391 = new Riddle("	小波比的一举一动都离不开绳子，为什么？ 	","	 小波是个木偶	", "儿童"	, "无");
		Riddle riddle392 = new Riddle("	小秦买了一辆全新的跑车，却不能开上马路，这是为什么？ 	","	 他买的是玩具跑车	", "儿童"	, "无");
		Riddle riddle393 = new Riddle("	阿研的口袋里共有10个硬币，漏掉了10个硬币，口袋里还有什么？ 	","	 一个破洞	", "儿童"	, "无");
		Riddle riddle394 = new Riddle("	何种动物最接近于人类? 	","	 寄生在人身体上的寄生虫	", "儿童"	, "无");
		Riddle riddle395 = new Riddle("	为什么两个孩子恰恰好？ 	","	 因为不孝有三	", "儿童"	, "无");
		Riddle riddle396 = new Riddle("	如果你生出的孩子只有一只右手你会怎么办? 	","	 废话，哪有人有两只右手的。	", "儿童"	, "无");
		Riddle riddle397 = new Riddle("	明明是个“错”字，为什么小华却偏偏说要“对”？ 	","	 的确是个错字呀	", "儿童"	, "无");
		Riddle riddle398 = new Riddle("	废除早自习会造成什么影响？ 	","	 让学生和家长可以多赖床半小时	", "儿童"	, "无");
		Riddle riddle399 = new Riddle("	丁丁拿着块石头向玻璃砸去，玻璃却没碎。为什么？ 	","	 没砸到	", "儿童"	, "无");
		Riddle riddle400 = new Riddle("	小孩子喜欢好什么？ 	","	 好奇	", "儿童"	, "无");
		Riddle riddle401 = new Riddle("	什么东西满屋走，但碰不着物件？ 	","	 声音	", "益智"	, "无");
		Riddle riddle402 = new Riddle("	一朵盛开在家里的花，却被关在笼子里。请问这是什么？ 	","	 电风扇	", "益智"	, "无");
		Riddle riddle403 = new Riddle("	什么東西越洗越脏？ 	","	 水	", "益智"	, "无");
		Riddle riddle404 = new Riddle("	什么鬼整天腾云驾雾？ 	","	 烟鬼	", "益智"	, "无");
		Riddle riddle405 = new Riddle("	在赛车比赛中，有辆车撞上大树，车子完全撞烂，开车者却毫发无伤，为什么？	","	 那是遥控车比赛	", "益智"	, "无");
		Riddle riddle406 = new Riddle("	什么东西载得动一百捆干草却托不起一粒沙子，日夜奔跑却离不开自己的卧床？	","	 河流	", "益智"	, "无");
		Riddle riddle407 = new Riddle("	什么事，你明明没有做，却要受罚? 	","	 回家做作业	", "益智"	, "无");
		Riddle riddle408 = new Riddle("	放大镜不能放大的东西是什么？ 	","	 角度	", "益智"	, "无");
		Riddle riddle409 = new Riddle("	小李说“我前的人是小王”，小王说“我前面的人是小李”怎么回事？	","	 很简单，他们面对面的站着	", "益智"	, "无");
		Riddle riddle410 = new Riddle("	少了一本书，猜一成语？ 	","	 缺一不可(book)	", "益智"	, "无");
		Riddle riddle411 = new Riddle("	小偷从现场逃走，为什么没有留下脚印？ 	","	 倒着走的	", "益智"	, "无");
		Riddle riddle412 = new Riddle("	有一种牛皮最容易被戳穿，那是什么牛皮？ 	","	 吹牛皮	", "益智"	, "无");
		Riddle riddle413 = new Riddle("	不打不相识，打两字称谓 	","	 战友	", "益智"	, "无");
		Riddle riddle414 = new Riddle("	谁是世界上最有恒心的画家？ 	","	 爱化妆的女人	", "益智"	, "无");
		Riddle riddle415 = new Riddle("	晴朗的天空，为什么没有太阳？？ 	","	 晚上当然没有太阳	", "益智"	, "无");
		Riddle riddle416 = new Riddle("	米的爸爸是谁？ 	","	 米的爸爸是蝶，蝶恋花	", "益智"	, "无");
		Riddle riddle417 = new Riddle("	水陆各半。（打一拉丁美洲国家名） 	","	 海地	", "益智"	, "无");
		Riddle riddle418 = new Riddle("	在火车站绝不可能发生什么事？ 	","	 既然不可能发生当然不能发生	", "益智"	, "无");
		Riddle riddle419 = new Riddle("	什么球不能踢? 	","	 火球	", "益智"	, "无");
		Riddle riddle420 = new Riddle("	一辆高速行驶的汽车在过一个90°的弯时，哪个轮子一定离开地面? 	","	 备用轮胎	", "益智"	, "无");
		Riddle riddle421 = new Riddle("	一座桥上面立有一牌，牌上写“不准过桥”。 但是很多人都照样不理睬，照样过去。你说为什么？ 	","	 这座桥的名字叫“不准过桥”	", "益智"	, "无");
		Riddle riddle422 = new Riddle("	什么水取之不尽，用之不竭？ 	","	 口水	", "益智"	, "无");
		Riddle riddle423 = new Riddle("	3个人3天用3桶水，9个人9天用几桶水？ 	","	 9捅	", "益智"	, "无");
		Riddle riddle424 = new Riddle("	地上有三只小鸟，打死一只，还剩几只？	","	 一只	", "益智"	, "无");
		Riddle riddle425 = new Riddle("	飞得最高的是什么? 	","	 人，他们飞到过月球	", "益智"	, "无");
		Riddle riddle426 = new Riddle("	9999个无（打一成语） 	","	 万无一失	", "益智"	, "无");
		Riddle riddle427 = new Riddle("	什么时候有人敲门，你绝不会说请进? 	","	 厕所	", "益智"	, "无");
		Riddle riddle428 = new Riddle("	世界上最长的单词是什么？ 	","	 微笑因为两个字母s里隔了一里（s-mile-s）	", "益智"	, "无");
		Riddle riddle429 = new Riddle("	什么柴不能烧？ 	","	 人才	", "益智"	, "无");
		Riddle riddle430 = new Riddle("	小玲放学回家后，发现自己忘了带钥匙，她该怎么做才能进家门呢？	","	 门没锁开开就好了	", "益智"	, "无");
		Riddle riddle431 = new Riddle("	有一个人被从几千米的高空掉下来的东西砸在头上，却没有受伤，为什么？	","	 砸下来的是雪花	", "益智"	, "无");
		Riddle riddle432 = new Riddle("	什么东西越热越爱出来？ 	","	 汗	", "益智"	, "无");
		Riddle riddle433 = new Riddle("	一幢大楼失火，很多人围观，却无人报警，为什么? 	","	 失火的正是警察局大楼	", "益智"	, "无");
		Riddle riddle434 = new Riddle("	有甲也有盔，有眼没有眉，无脚会赶路，有翅不会飞，这是什么？ 	","	 鱼	", "益智"	, "无");
		Riddle riddle435 = new Riddle("	一个人午后在太阳下走，却看不见自己的影子。为什么？ 	","	 阴雨天遮住了太阳	", "益智"	, "无");
		Riddle riddle436 = new Riddle("	八十多了一横，打一字。 	","	 平	", "益智"	, "无");
		Riddle riddle437 = new Riddle("	怎样使用最简单的方法使X+I=IX等式成立？ 	","	 I+X	", "益智"	, "无");
		Riddle riddle438 = new Riddle("	什么戏人人都演过？ 	","	 游戏	", "益智"	, "无");
		Riddle riddle439 = new Riddle("	什么人在刀刃上生活? 	","	 滑冰运动员	", "益智"	, "无");
		Riddle riddle440 = new Riddle("	有一个东西，你能用左手拿，不能用右手拿，这东西是什么？ 	","	 自己的右手	", "益智"	, "无");
		Riddle riddle441 = new Riddle("	一个可以大可以小的地方是哪里？ 	","	 厕所	", "益智"	, "无");
		Riddle riddle442 = new Riddle("	小王走路从来脚不沾地，这是为什么? 	","	 因为穿着鞋子	", "益智"	, "无");
		Riddle riddle443 = new Riddle("	什么人是人们说时很崇拜，但却不想见到的人？ 	","	 上帝	", "益智"	, "无");
		Riddle riddle444 = new Riddle("	在餐厅中吃完饭发现没带钱，怎么办？ 	","	 刷卡或吃赊帐	", "益智"	, "无");
		Riddle riddle445 = new Riddle("	什么东西有头无脚？ 	","	 砖头	", "益智"	, "无");
		Riddle riddle446 = new Riddle("	一次宴会上，一对夫妻同客人共握手48次，问这次宴会上共有几人？ 	","	 26人	", "益智"	, "无");
		Riddle riddle447 = new Riddle("	桌子上有12支点燃的蜡烛，先被风吹灭了3根，不久又一阵风吹灭了2根，最后桌子上还剩几根蜡烛？ 	","	 5根，因为没被吹灭的都燃完了	", "益智"	, "无");
		Riddle riddle448 = new Riddle("	用三个3组成一个最大的数? 	","	 3的33次方	", "益智"	, "无");
		Riddle riddle449 = new Riddle("	刘邦破咸阳—城市名一 	","	 秦皇岛	", "益智"	, "无");
		Riddle riddle450 = new Riddle("	小凯开着车子，却始终到不了目的地，为什么？ 	","	 他开的是公园里的环行车	", "益智"	, "无");
		Riddle riddle451 = new Riddle("	什么样的情况下，一加一绝对不等于二？	","	 一大杯水加进一斤面粉中，只会等于一块面团	", "益智"	, "无");
		Riddle riddle452 = new Riddle("	什么样的水不能喝？ 	","	 薪水	", "益智"	, "无");
		Riddle riddle453 = new Riddle("	什么鸭子用两只脚走路？ 	","	 所有的鸭子都是用两只脚走路	", "益智"	, "无");
		Riddle riddle454 = new Riddle("	1+1不是2、王、11是什么？ 	","	 丰	", "益智"	, "无");
		Riddle riddle455 = new Riddle("	什么东西越吃越感到饿？ 	","	 消化药	", "益智"	, "无");
		Riddle riddle456 = new Riddle("	谁最喜欢添油加醋？？ 	","	 厨师	", "益智"	, "无");
		Riddle riddle457 = new Riddle("	锐锐他能轻而易举地把一只倒悬的杯子装满水，而且不用任何东西挡住瓶口，他是怎样做的呢？ 	","	 将杯子倒扣在装满水的盆子里。	", "益智"	, "无");
		Riddle riddle458 = new Riddle("	小赵买一张奖票，中了一等奖，去领奖却不给? 	","	 没有到领奖的日期	", "益智"	, "无");
		Riddle riddle459 = new Riddle("	塑料袋里有六个橘子，如何均分给三个小孩，而塑料袋里仍有二个橘子？（不可以分开橘子） 	","	 当然是一个人两个桔子，只是一个连塑料袋一起给他.	", "益智"	, "无");
		Riddle riddle460 = new Riddle("	什么人最喜欢日光浴？ 	","	 植物人(光合作用)	", "益智"	, "无");
		Riddle riddle461 = new Riddle("	有三个小孩子正在猜拳，一个出剪刀，一个出石头，一个出布，请问三个小孩子的手指共有几根？ 	","	 三十根	", "益智"	, "无");
		Riddle riddle462 = new Riddle("	池无水，地无土(打一字) ？ 	","	 也	", "益智"	, "无");
		Riddle riddle463 = new Riddle("	用什么方法可以使人不喝水？ 	","	 把水改名字	", "益智"	, "无");
		Riddle riddle464 = new Riddle("	什么油不能点燃？ 	","	 酱油	", "益智"	, "无");
		Riddle riddle465 = new Riddle("	别人请你吃什么需要你自己花钱？ 	","	 吃官司	", "益智"	, "无");
		Riddle riddle466 = new Riddle("	世界上哪个地方下午比早上先到？ 	","	 在字典里	", "益智"	, "无");
		Riddle riddle467 = new Riddle("	远在外地工作的浪人寄了封信回家慰问，里面还夹了张照片，但为什么他家人收到信后却迟迟不肯打开看呢? 	","	 粗心的浪人把勿折写成了勿拆	", "益智"	, "无");
		Riddle riddle468 = new Riddle("	什么鬼大家都喜欢啊？ 	","	 淘气鬼	", "益智"	, "无");
		Riddle riddle469 = new Riddle("	有一种水果，没吃之前是绿色的，吃下去是红色的，吐出时却是黑色的，請問是请问这是什么水果? 	","	 西瓜	", "益智"	, "无");
		Riddle riddle470 = new Riddle("	山岗上有三只狐狸，猎人开枪打死了一只，问山岗上还有几只狐狸？ 	","	 一只	", "益智"	, "无");
		Riddle riddle471 = new Riddle("	车子应该靠右行使才对，为什么杨先生靠左行使却没事？	","	 因为他正行驶在靠左行驶的国家	", "益智"	, "无");
		Riddle riddle472 = new Riddle("	什么车子寸步难行？（除了坏车子） 	","	 风车	", "益智"	, "无");
		Riddle riddle473 = new Riddle("	什么越冷越爱出来？ 	","	 鼻涕	", "益智"	, "无");
		Riddle riddle474 = new Riddle("	桥下只能限高十米，但是船上的货物已超过十米，该怎么办呢？	","	 拿几块大石头放到船上船就会下沉一些	", "益智"	, "无");
		Riddle riddle475 = new Riddle("	小张一直朝北走，走着走着他又没有转身可是却走到了正南方，为什么?	","	 他越过北极点在向前走就是南方	", "益智"	, "无");
		Riddle riddle476 = new Riddle("	什么桶永远装不满？ 	","	 马桶	", "益智"	, "无");
		Riddle riddle477 = new Riddle("	李伯伯一共有7个儿子，这7个儿子又各有一个妹妹，那么，李伯伯一共有几个子女？	","	 八个子女妹妹最小	", "益智"	, "无");
		Riddle riddle478 = new Riddle("	煮一个蛋要四分钟，煮八个蛋要几分钟？ 	","	 四分钟	", "益智"	, "无");
		Riddle riddle479 = new Riddle("	两只蚂蚁抬根杠，一只蚂蚁杠上望 	","	 六	", "益智"	, "无");
		Riddle riddle480 = new Riddle("	什么老鼠用两只脚走路？ 	","	 米老鼠	", "益智"	, "无");
		Riddle riddle481 = new Riddle("	促膝而谈，猜一个物理理论？ 	","	 相对论	", "很难"	, "无");
		Riddle riddle482 = new Riddle("	患者张开嘴巴之后，牙医吓了一跳说：“哇！你的牙齿蛀了好大一个洞 ！哇！你的牙齿蛀了好大一个洞，一个洞！”请问他为什么要说两遍呢？ 	","	 因为那是回音	", "很难"	, "无");
		Riddle riddle483 = new Riddle("	什么果不能吃？ 	","	 后果	", "很难"	, "无");
		Riddle riddle484 = new Riddle("	4+4+4+4（猜一种水果） 	","	 16，石榴	", "很难"	, "无");
		Riddle riddle485 = new Riddle("	小张开车，不小心撞上电线杆发生车祸，警察到达时车上有个死人，小张说这与他无关，警察也相信了，为什么？ 	","	 小张开灵车	", "很难"	, "无");
		Riddle riddle486 = new Riddle("	有个地方发生了火灾，虽然有很多人在救火，但就是没人报火警，为什么?	","	 消防队着火了	", "很难"	, "无");
		Riddle riddle487 = new Riddle("	什么酒不能喝? 	","	 碘酒	", "很难"	, "无");
		Riddle riddle488 = new Riddle("	哪一件衣服最耐穿？ 	","	 最不喜欢的那件	", "很难"	, "无");
		Riddle riddle489 = new Riddle("	妈妈叫小民去拿碟子来装菜，小民拿来了，却被骂了一顿，为什么？	","	 他拿的是光喋	", "很难"	, "无");
		Riddle riddle490 = new Riddle("	离婚的主要起因是什么？ 	","	 结婚	", "很难"	, "无");
		Riddle riddle491 = new Riddle("	四天三夜的露营活动，最令人难忘的是哪一夜？ 	","	 宵夜	", "很难"	, "无");
		Riddle riddle492 = new Riddle("	用什么方法立刻可以找到遗失的图钉？ 	","	 光着脚走	", "很难"	, "无");
		Riddle riddle493 = new Riddle("	一位服装模特儿小姐，即使在平日也穿着未经发表的新款服饰，但她常常看到穿着和她完全相同服饰的人。这是为什么？ 	","	 因为她看到镜子中的自己	", "很难"	, "无");
		Riddle riddle494 = new Riddle("	中国哪个地方的东西最不便宜？ 	","	 贵州	", "很难"	, "无");
		Riddle riddle495 = new Riddle("	海关大钟一昼夜里时针和分钟重合多少次？ 	","	 23	", "很难"	, "无");
		Riddle riddle496 = new Riddle("	母亲节那天，你如果不想让母亲洗碗，又不想自己动手的话，你该怎么办？	","	 跟她说：妈，留着明天洗吧	", "很难"	, "无");
		Riddle riddle497 = new Riddle("	小张被关在一间并没有上锁的房间里，可是他使出吃奶的力气也不能把门拉开，这是怎么回事？ 	","	 推开门就行	", "很难"	, "无");
		Riddle riddle498 = new Riddle("	猜猜什么东西，可以洗，不能晒，可以吃，不能吞？ 	","	 麻将	", "很难"	, "无");
		Riddle riddle499 = new Riddle("	男人在一起喝酒，为什么非划拳不可？ 	","	 敬酒不吃吃罚酒	", "很难"	, "无");
		Riddle riddle500 = new Riddle("	动物园里，小明紧挨着老虎合影留念，老虎却没有咬他，为什么？	","	 那是只假老虎	", "很难"	, "无");
		Riddle riddle501 = new Riddle("	一头牛加一捆草等于什么？ 	","	 还是一头牛	", "很难"	, "无");
		Riddle riddle502 = new Riddle("	什么样的情况下，一加一绝对不等于二？	","	 一大杯水加进一斤面粉中，只会等于一块面团	", "很难"	, "无");
		Riddle riddle503 = new Riddle("	小波比的一举一动都离不开绳子，为什么？ 	","	 小波是个木偶	", "很难"	, "无");
		Riddle riddle504 = new Riddle("	日月潭的中间是什么？ 	","	 是月字	", "很难"	, "无");
		Riddle riddle505 = new Riddle("	拿手杖的瞎子阿明，走到一处未加盖的下水道洞口前，为什么没有失足掉进洞里？	","	 因为忘了带手杖想起来回家拿了	", "很难"	, "无");
		Riddle riddle506 = new Riddle("	一对健康的夫妇，为什么会生出没有眼睛的婴儿? 	","	 鸡生蛋	", "很难"	, "无");
		Riddle riddle507 = new Riddle("	什么东西别人请你吃，但你自己还是要付钱？ 	","	 吃官司	", "很难"	, "无");
		Riddle riddle508 = new Riddle("	什么地方看到的月亮最大？ 	","	 月球上	", "很难"	, "无");
		Riddle riddle509 = new Riddle("	二十世纪最出风头的超级巨星是哪一位？ 	","	 海尔波普慧星，千年才见一次	", "很难"	, "无");
		Riddle riddle510 = new Riddle("	3个人3天用3桶水，9个人9天用几桶水？ 	","	 9捅	", "很难"	, "无");
		Riddle riddle511 = new Riddle("	为什么吃完晚餐后，全家都喜欢坐在电视机前看电视？ 	","	 因为站久了脚会酸	", "很难"	, "无");
		Riddle riddle512 = new Riddle("	释迦牟尼是男人还是女人？ 	","	 都不是，他是神	", "很难"	, "无");
		Riddle riddle513 = new Riddle("	为什么有人说建立在金钱基础上的婚姻是最牢固的？	","	 铜婚，银婚，金婚……越老越牢固	", "很难"	, "无");
		Riddle riddle514 = new Riddle("	什么布剪不断？ 	","	 瀑布	", "很难"	, "无");
		Riddle riddle515 = new Riddle("	小明对小华说：“我可以坐在一个你永远也坐不到的地方！”他坐在哪里？	","	 小华的身上	", "很难"	, "无");
		Riddle riddle516 = new Riddle("	老子为什么要骑青牛出海关？ 	","	 老子高兴	", "很难"	, "无");
		Riddle riddle517 = new Riddle("	小陈半夜吃泡面，为什么一面吃，一面眼盯着表？ 	","	 那包面的食用期到今天	", "很难"	, "无");
		Riddle riddle518 = new Riddle("	有什么办法可以保住母鸡性命免遭主人宰杀? 	","	 想办法每天下一个蛋	", "很难"	, "无");
		Riddle riddle519 = new Riddle("	蛋要怎么买，才不会买到里面已经孵出了小鸡的蛋？ 	","	 买鸭蛋	", "很难"	, "无");
		Riddle riddle520 = new Riddle("	有一天小董上完物理课后，突然想效法牛顿，就到苹果树下，这时也刚好掉下一颗苹果，砸到小董的头，你猜小董怎么说？ 	","	 这个苹果是熟的	", "很难"	, "无");
		Riddle riddle521 = new Riddle("	小明一家人在客厅里，明明听到有人喊：“救命啊，失火了，为什么他们一家人动也不动？？？ 	","	 因为他们在看电视	", "很难"	, "无");
		Riddle riddle522 = new Riddle("	胖姐阿英站上人体秤时，为何指针却只指着5？ 	","	 指针已转过一圈了	", "很难"	, "无");
		Riddle riddle523 = new Riddle("	动物园的大象死了，为什么大象管理员哭得那么伤心？	","	 他想到要挖那么大一个坑，所以就……	", "很难"	, "无");
		Riddle riddle524 = new Riddle("	10除2却不等于五，为什么？ 	","	 情报小组除去两名汉奸还有8名	", "很难"	, "无");
		Riddle riddle525 = new Riddle("	老张不小心吞了一枚金币，为什么到十年后才去手术取出来呢？	","	 因为当时不急着用钱	", "很难"	, "无");
		Riddle riddle526 = new Riddle("	在一次监察严密的考试中，有两个学生交了一模一样的考卷。主考官发现后，却并没有认为他们作弊，这是什么原因？ 	","	 二张考卷交得都是白卷	", "很难"	, "无");
		Riddle riddle527 = new Riddle("	每个成功男人背后有一个女人，那一个失败的男人背后会有什么？	","	 有太多的女人	", "很难"	, "无");
		Riddle riddle528 = new Riddle("	两个棋友一天共下了9盘棋，在没有和局的情况下他俩赢的次数相同，怎么回事?	","	 9盘不全是他们两个人一起下的	", "很难"	, "无");
		Riddle riddle529 = new Riddle("	农夫养了10头牛，为什么只有19只角？	","	 因为一只是犀牛	", "很难"	, "无");
		Riddle riddle530 = new Riddle("	在路上，它翻了一个跟斗，接着又翻了一次（猜4字成语）? 	","	 三翻两次	", "很难"	, "无");
		Riddle riddle531 = new Riddle("	米的妈妈是谁？ 	","	 米的妈妈是花，花生米	", "很难"	, "无");
		Riddle riddle532 = new Riddle("	两个人住在一个胡同里，只隔几步路，他们同在一个工厂上班，但每天出门上班，却总一个向左，一个向右，为什么? 	","	 他们住对门	", "很难"	, "无");
		Riddle riddle533 = new Riddle("	有一位大师武功了得，他在下雨天不带任何防雨物品出门，全身都被淋湿了，可是头发一点没湿，怎么回事? 	","	 他是和尚，没有头发	", "很难"	, "无");
		Riddle riddle534 = new Riddle("	这封信是两颗蛋做的（四字成语）? 	","	 信誓旦旦(蛋蛋)	", "很难"	, "无");
		Riddle riddle535 = new Riddle("	卖水的人看到河会怎么想？ 	","	 这些都是钱	", "很难"	, "无");
		Riddle riddle536 = new Riddle("	地球上什么东西每天要走的距离最远? 	","	 地球	", "很难"	, "无");
		Riddle riddle537 = new Riddle("	老师给萨姆布置了一篇作文，题目是；什么是懒惰。萨姆用最简短的文字写下了这篇作文，他是怎么写的？ 	","	 这就是懒惰	", "很难"	, "无");
		Riddle riddle538 = new Riddle("	班长告诉菜鸟，当拉开手榴弹的保险之后，口中先数五秒再投掷出去，菜鸟一切都按班长指示动作，但仍被炸死了，为什么？ 	","	 因为菜鸟有口吃	", "很难"	, "无");
		Riddle riddle539 = new Riddle("	5只鸡，5天生了5个蛋。100天内要100个蛋，需要多少只鸡？？ 	","	 依然是五只鸡.	", "很难"	, "无");
		Riddle riddle540 = new Riddle("	哪一个字永远写不好? 	","	 “坏”字	", "很难"	, "无");
		Riddle riddle541 = new Riddle("	锐锐他能轻而易举地把一只倒悬的杯子装满水，而且不用任何东西挡住瓶口，他是怎样做的呢？ 	","	 将杯子倒扣在装满水的盆子里。	", "很难"	, "无");
		Riddle riddle542 = new Riddle("	喝工夫茶(打一成语)？ 	","	 苦尽甘来	", "很难"	, "无");
		Riddle riddle543 = new Riddle("	阿火在营光日的考试全部答对，为什么却没得到满分？ 	","	 因为考的是是非题	", "很难"	, "无");
		Riddle riddle544 = new Riddle("	二姑娘（打一字） 	","	 姿	", "很难"	, "无");
		Riddle riddle545 = new Riddle("	一群惧内的大丈夫们正聚集在一起商量怎样重振男子汉的雄风，突然听说他们的老婆来了，大家四处逃窜，惟独一人没有跑，为什么？ 	","	 吓死了	", "很难"	, "无");
		Riddle riddle546 = new Riddle("	当你对一件事忍无可忍时，你会怎么处理？ 	","	 赶快上厕所	", "很难"	, "无");
		Riddle riddle547 = new Riddle("	怀孕的母狗怕人踢它，可是有个家伙踢它，它既不躲避也不生气，为什么？	","	 因为那家伙在他的肚子里踢	", "很难"	, "无");
		Riddle riddle548 = new Riddle("	有一个人，他是你父母生的，但他却不是你的兄弟姐妹，他是谁？ 	","	 你自己	", "很难"	, "无");
		Riddle riddle549 = new Riddle("	某个人到外国去了，可是，周围全是中国人，这是怎么回事？ 	","	 在中国	", "很难"	, "无");
		Riddle riddle550 = new Riddle("	要形容女孩子好看，说什么话她最高兴？ 	","	 谎话	", "很难"	, "无");
		Riddle riddle551 = new Riddle("	什么東西越洗越脏？ 	","	 水	", "很难"	, "无");
		Riddle riddle552 = new Riddle("	足球比赛中间休息的时候，爸爸问他的儿子：放在右脚旁边而左脚碰不到的是什么东西？儿子灵机一动就答对了，你知道吗？ 	","	 是左脚	", "很难"	, "无");
		Riddle riddle553 = new Riddle("	有一个人被从几千米的高空掉下来的东西砸在头上，却没有受伤，为什么？	","	 砸下来的是雪花	", "很难"	, "无");
		Riddle riddle554 = new Riddle("	世界上什么最大？ 	","	 眼皮	", "很难"	, "无");
		Riddle riddle555 = new Riddle("	人为什么要生两只耳朵？ 	","	 兼听则明	", "很难"	, "无");
		Riddle riddle556 = new Riddle("	张飞的妈妈姓什么？	","	 吴，无（吴）事（氏）生非（飞）	", "很难"	, "无");
		Riddle riddle557 = new Riddle("	茉莉花，太阳花，玫瑰花，哪一朵花最没力 ?	","	 茉莉花因为好一朵没力(茉莉花)花	", "很难"	, "无");
		Riddle riddle558 = new Riddle("	一只毛毛虫（八只脚）走上一堆牛粪，下地以后却发现只有六只脚印，为 什么？	","	 牛粪很臭两只脚捏住了鼻子	", "很难"	, "无");
		Riddle riddle559 = new Riddle("	如果苹果没落在牛顿头顶上，会落到哪里？ 	","	 地上	", "很难"	, "无");
		Riddle riddle560 = new Riddle("	有一段100公尺长的铁轨上面每隔1公分放一条横木，请问共有几条横木？	","	 0，因为钢轨上不放横木	", "很难"	, "无");



		dbRManager.insert(riddle1);
		dbRManager.insert(riddle2);
		dbRManager.insert(riddle3);
		dbRManager.insert(riddle4);
		dbRManager.insert(riddle5);
		dbRManager.insert(riddle6);
		dbRManager.insert(riddle7);
		dbRManager.insert(riddle8);
		dbRManager.insert(riddle9);
		dbRManager.insert(riddle10);
		dbRManager.insert(riddle11);
		dbRManager.insert(riddle12);
		dbRManager.insert(riddle13);
		dbRManager.insert(riddle14);
		dbRManager.insert(riddle15);
		dbRManager.insert(riddle16);
		dbRManager.insert(riddle17);
		dbRManager.insert(riddle18);
		dbRManager.insert(riddle19);
		dbRManager.insert(riddle20);
		dbRManager.insert(riddle21);
		dbRManager.insert(riddle22);
		dbRManager.insert(riddle23);
		dbRManager.insert(riddle24);
		dbRManager.insert(riddle25);
		dbRManager.insert(riddle26);
		dbRManager.insert(riddle27);
		dbRManager.insert(riddle28);
		dbRManager.insert(riddle29);
		dbRManager.insert(riddle30);
		dbRManager.insert(riddle31);
		dbRManager.insert(riddle32);
		dbRManager.insert(riddle33);
		dbRManager.insert(riddle34);
		dbRManager.insert(riddle35);
		dbRManager.insert(riddle36);
		dbRManager.insert(riddle37);
		dbRManager.insert(riddle38);
		dbRManager.insert(riddle39);
		dbRManager.insert(riddle40);
		dbRManager.insert(riddle41);
		dbRManager.insert(riddle42);
		dbRManager.insert(riddle43);
		dbRManager.insert(riddle44);
		dbRManager.insert(riddle45);
		dbRManager.insert(riddle46);
		dbRManager.insert(riddle47);
		dbRManager.insert(riddle48);
		dbRManager.insert(riddle49);
		dbRManager.insert(riddle50);
		dbRManager.insert(riddle51);
		dbRManager.insert(riddle52);
		dbRManager.insert(riddle53);
		dbRManager.insert(riddle54);
		dbRManager.insert(riddle55);
		dbRManager.insert(riddle56);
		dbRManager.insert(riddle57);
		dbRManager.insert(riddle58);
		dbRManager.insert(riddle59);
		dbRManager.insert(riddle60);
		dbRManager.insert(riddle61);
		dbRManager.insert(riddle62);
		dbRManager.insert(riddle63);
		dbRManager.insert(riddle64);
		dbRManager.insert(riddle65);
		dbRManager.insert(riddle66);
		dbRManager.insert(riddle67);
		dbRManager.insert(riddle68);
		dbRManager.insert(riddle69);
		dbRManager.insert(riddle70);
		dbRManager.insert(riddle71);
		dbRManager.insert(riddle72);
		dbRManager.insert(riddle73);
		dbRManager.insert(riddle74);
		dbRManager.insert(riddle75);
		dbRManager.insert(riddle76);
		dbRManager.insert(riddle77);
		dbRManager.insert(riddle78);
		dbRManager.insert(riddle79);
		dbRManager.insert(riddle80);
		dbRManager.insert(riddle81);
		dbRManager.insert(riddle82);
		dbRManager.insert(riddle83);
		dbRManager.insert(riddle84);
		dbRManager.insert(riddle85);
		dbRManager.insert(riddle86);
		dbRManager.insert(riddle87);
		dbRManager.insert(riddle88);
		dbRManager.insert(riddle89);
		dbRManager.insert(riddle90);
		dbRManager.insert(riddle91);
		dbRManager.insert(riddle92);
		dbRManager.insert(riddle93);
		dbRManager.insert(riddle94);
		dbRManager.insert(riddle95);
		dbRManager.insert(riddle96);
		dbRManager.insert(riddle97);
		dbRManager.insert(riddle98);
		dbRManager.insert(riddle99);
		dbRManager.insert(riddle100);
		dbRManager.insert(riddle101);
		dbRManager.insert(riddle102);
		dbRManager.insert(riddle103);
		dbRManager.insert(riddle104);
		dbRManager.insert(riddle105);
		dbRManager.insert(riddle106);
		dbRManager.insert(riddle107);
		dbRManager.insert(riddle108);
		dbRManager.insert(riddle109);
		dbRManager.insert(riddle110);
		dbRManager.insert(riddle111);
		dbRManager.insert(riddle112);
		dbRManager.insert(riddle113);
		dbRManager.insert(riddle114);
		dbRManager.insert(riddle115);
		dbRManager.insert(riddle116);
		dbRManager.insert(riddle117);
		dbRManager.insert(riddle118);
		dbRManager.insert(riddle119);
		dbRManager.insert(riddle120);
		dbRManager.insert(riddle121);
		dbRManager.insert(riddle122);
		dbRManager.insert(riddle123);
		dbRManager.insert(riddle124);
		dbRManager.insert(riddle125);
		dbRManager.insert(riddle126);
		dbRManager.insert(riddle127);
		dbRManager.insert(riddle128);
		dbRManager.insert(riddle129);
		dbRManager.insert(riddle130);
		dbRManager.insert(riddle131);
		dbRManager.insert(riddle132);
		dbRManager.insert(riddle133);
		dbRManager.insert(riddle134);
		dbRManager.insert(riddle135);
		dbRManager.insert(riddle136);
		dbRManager.insert(riddle137);
		dbRManager.insert(riddle138);
		dbRManager.insert(riddle139);
		dbRManager.insert(riddle140);
		dbRManager.insert(riddle141);
		dbRManager.insert(riddle142);
		dbRManager.insert(riddle143);
		dbRManager.insert(riddle144);
		dbRManager.insert(riddle145);
		dbRManager.insert(riddle146);
		dbRManager.insert(riddle147);
		dbRManager.insert(riddle148);
		dbRManager.insert(riddle149);
		dbRManager.insert(riddle150);
		dbRManager.insert(riddle151);
		dbRManager.insert(riddle152);
		dbRManager.insert(riddle153);
		dbRManager.insert(riddle154);
		dbRManager.insert(riddle155);
		dbRManager.insert(riddle156);
		dbRManager.insert(riddle157);
		dbRManager.insert(riddle158);
		dbRManager.insert(riddle159);
		dbRManager.insert(riddle160);
		dbRManager.insert(riddle161);
		dbRManager.insert(riddle162);
		dbRManager.insert(riddle163);
		dbRManager.insert(riddle164);
		dbRManager.insert(riddle165);
		dbRManager.insert(riddle166);
		dbRManager.insert(riddle167);
		dbRManager.insert(riddle168);
		dbRManager.insert(riddle169);
		dbRManager.insert(riddle170);
		dbRManager.insert(riddle171);
		dbRManager.insert(riddle172);
		dbRManager.insert(riddle173);
		dbRManager.insert(riddle174);
		dbRManager.insert(riddle175);
		dbRManager.insert(riddle176);
		dbRManager.insert(riddle177);
		dbRManager.insert(riddle178);
		dbRManager.insert(riddle179);
		dbRManager.insert(riddle180);
		dbRManager.insert(riddle181);
		dbRManager.insert(riddle182);
		dbRManager.insert(riddle183);
		dbRManager.insert(riddle184);
		dbRManager.insert(riddle185);
		dbRManager.insert(riddle186);
		dbRManager.insert(riddle187);
		dbRManager.insert(riddle188);
		dbRManager.insert(riddle189);
		dbRManager.insert(riddle190);
		dbRManager.insert(riddle191);
		dbRManager.insert(riddle192);
		dbRManager.insert(riddle193);
		dbRManager.insert(riddle194);
		dbRManager.insert(riddle195);
		dbRManager.insert(riddle196);
		dbRManager.insert(riddle197);
		dbRManager.insert(riddle198);
		dbRManager.insert(riddle199);
		dbRManager.insert(riddle200);
		dbRManager.insert(riddle201);
		dbRManager.insert(riddle202);
		dbRManager.insert(riddle203);
		dbRManager.insert(riddle204);
		dbRManager.insert(riddle205);
		dbRManager.insert(riddle206);
		dbRManager.insert(riddle207);
		dbRManager.insert(riddle208);
		dbRManager.insert(riddle209);
		dbRManager.insert(riddle210);
		dbRManager.insert(riddle211);
		dbRManager.insert(riddle212);
		dbRManager.insert(riddle213);
		dbRManager.insert(riddle214);
		dbRManager.insert(riddle215);
		dbRManager.insert(riddle216);
		dbRManager.insert(riddle217);
		dbRManager.insert(riddle218);
		dbRManager.insert(riddle219);
		dbRManager.insert(riddle220);
		dbRManager.insert(riddle221);
		dbRManager.insert(riddle222);
		dbRManager.insert(riddle223);
		dbRManager.insert(riddle224);
		dbRManager.insert(riddle225);
		dbRManager.insert(riddle226);
		dbRManager.insert(riddle227);
		dbRManager.insert(riddle228);
		dbRManager.insert(riddle229);
		dbRManager.insert(riddle230);
		dbRManager.insert(riddle231);
		dbRManager.insert(riddle232);
		dbRManager.insert(riddle233);
		dbRManager.insert(riddle234);
		dbRManager.insert(riddle235);
		dbRManager.insert(riddle236);
		dbRManager.insert(riddle237);
		dbRManager.insert(riddle238);
		dbRManager.insert(riddle239);
		dbRManager.insert(riddle240);
		dbRManager.insert(riddle241);
		dbRManager.insert(riddle242);
		dbRManager.insert(riddle243);
		dbRManager.insert(riddle244);
		dbRManager.insert(riddle245);
		dbRManager.insert(riddle246);
		dbRManager.insert(riddle247);
		dbRManager.insert(riddle248);
		dbRManager.insert(riddle249);
		dbRManager.insert(riddle250);
		dbRManager.insert(riddle251);
		dbRManager.insert(riddle252);
		dbRManager.insert(riddle253);
		dbRManager.insert(riddle254);
		dbRManager.insert(riddle255);
		dbRManager.insert(riddle256);
		dbRManager.insert(riddle257);
		dbRManager.insert(riddle258);
		dbRManager.insert(riddle259);
		dbRManager.insert(riddle260);
		dbRManager.insert(riddle261);
		dbRManager.insert(riddle262);
		dbRManager.insert(riddle263);
		dbRManager.insert(riddle264);
		dbRManager.insert(riddle265);
		dbRManager.insert(riddle266);
		dbRManager.insert(riddle267);
		dbRManager.insert(riddle268);
		dbRManager.insert(riddle269);
		dbRManager.insert(riddle270);
		dbRManager.insert(riddle271);
		dbRManager.insert(riddle272);
		dbRManager.insert(riddle273);
		dbRManager.insert(riddle274);
		dbRManager.insert(riddle275);
		dbRManager.insert(riddle276);
		dbRManager.insert(riddle277);
		dbRManager.insert(riddle278);
		dbRManager.insert(riddle279);
		dbRManager.insert(riddle280);
		dbRManager.insert(riddle281);
		dbRManager.insert(riddle282);
		dbRManager.insert(riddle283);
		dbRManager.insert(riddle284);
		dbRManager.insert(riddle285);
		dbRManager.insert(riddle286);
		dbRManager.insert(riddle287);
		dbRManager.insert(riddle288);
		dbRManager.insert(riddle289);
		dbRManager.insert(riddle290);
		dbRManager.insert(riddle291);
		dbRManager.insert(riddle292);
		dbRManager.insert(riddle293);
		dbRManager.insert(riddle294);
		dbRManager.insert(riddle295);
		dbRManager.insert(riddle296);
		dbRManager.insert(riddle297);
		dbRManager.insert(riddle298);
		dbRManager.insert(riddle299);
		dbRManager.insert(riddle300);
		dbRManager.insert(riddle301);
		dbRManager.insert(riddle302);
		dbRManager.insert(riddle303);
		dbRManager.insert(riddle304);
		dbRManager.insert(riddle305);
		dbRManager.insert(riddle306);
		dbRManager.insert(riddle307);
		dbRManager.insert(riddle308);
		dbRManager.insert(riddle309);
		dbRManager.insert(riddle310);
		dbRManager.insert(riddle311);
		dbRManager.insert(riddle312);
		dbRManager.insert(riddle313);
		dbRManager.insert(riddle314);
		dbRManager.insert(riddle315);
		dbRManager.insert(riddle316);
		dbRManager.insert(riddle317);
		dbRManager.insert(riddle318);
		dbRManager.insert(riddle319);
		dbRManager.insert(riddle320);
		dbRManager.insert(riddle321);
		dbRManager.insert(riddle322);
		dbRManager.insert(riddle323);
		dbRManager.insert(riddle324);
		dbRManager.insert(riddle325);
		dbRManager.insert(riddle326);
		dbRManager.insert(riddle327);
		dbRManager.insert(riddle328);
		dbRManager.insert(riddle329);
		dbRManager.insert(riddle330);
		dbRManager.insert(riddle331);
		dbRManager.insert(riddle332);
		dbRManager.insert(riddle333);
		dbRManager.insert(riddle334);
		dbRManager.insert(riddle335);
		dbRManager.insert(riddle336);
		dbRManager.insert(riddle337);
		dbRManager.insert(riddle338);
		dbRManager.insert(riddle339);
		dbRManager.insert(riddle340);
		dbRManager.insert(riddle341);
		dbRManager.insert(riddle342);
		dbRManager.insert(riddle343);
		dbRManager.insert(riddle344);
		dbRManager.insert(riddle345);
		dbRManager.insert(riddle346);
		dbRManager.insert(riddle347);
		dbRManager.insert(riddle348);
		dbRManager.insert(riddle349);
		dbRManager.insert(riddle350);
		dbRManager.insert(riddle351);
		dbRManager.insert(riddle352);
		dbRManager.insert(riddle353);
		dbRManager.insert(riddle354);
		dbRManager.insert(riddle355);
		dbRManager.insert(riddle356);
		dbRManager.insert(riddle357);
		dbRManager.insert(riddle358);
		dbRManager.insert(riddle359);
		dbRManager.insert(riddle360);
		dbRManager.insert(riddle361);
		dbRManager.insert(riddle362);
		dbRManager.insert(riddle363);
		dbRManager.insert(riddle364);
		dbRManager.insert(riddle365);
		dbRManager.insert(riddle366);
		dbRManager.insert(riddle367);
		dbRManager.insert(riddle368);
		dbRManager.insert(riddle369);
		dbRManager.insert(riddle370);
		dbRManager.insert(riddle371);
		dbRManager.insert(riddle372);
		dbRManager.insert(riddle373);
		dbRManager.insert(riddle374);
		dbRManager.insert(riddle375);
		dbRManager.insert(riddle376);
		dbRManager.insert(riddle377);
		dbRManager.insert(riddle378);
		dbRManager.insert(riddle379);
		dbRManager.insert(riddle380);
		dbRManager.insert(riddle381);
		dbRManager.insert(riddle382);
		dbRManager.insert(riddle383);
		dbRManager.insert(riddle384);
		dbRManager.insert(riddle385);
		dbRManager.insert(riddle386);
		dbRManager.insert(riddle387);
		dbRManager.insert(riddle388);
		dbRManager.insert(riddle389);
		dbRManager.insert(riddle390);
		dbRManager.insert(riddle391);
		dbRManager.insert(riddle392);
		dbRManager.insert(riddle393);
		dbRManager.insert(riddle394);
		dbRManager.insert(riddle395);
		dbRManager.insert(riddle396);
		dbRManager.insert(riddle397);
		dbRManager.insert(riddle398);
		dbRManager.insert(riddle399);
		dbRManager.insert(riddle400);
		dbRManager.insert(riddle401);
		dbRManager.insert(riddle402);
		dbRManager.insert(riddle403);
		dbRManager.insert(riddle404);
		dbRManager.insert(riddle405);
		dbRManager.insert(riddle406);
		dbRManager.insert(riddle407);
		dbRManager.insert(riddle408);
		dbRManager.insert(riddle409);
		dbRManager.insert(riddle410);
		dbRManager.insert(riddle411);
		dbRManager.insert(riddle412);
		dbRManager.insert(riddle413);
		dbRManager.insert(riddle414);
		dbRManager.insert(riddle415);
		dbRManager.insert(riddle416);
		dbRManager.insert(riddle417);
		dbRManager.insert(riddle418);
		dbRManager.insert(riddle419);
		dbRManager.insert(riddle420);
		dbRManager.insert(riddle421);
		dbRManager.insert(riddle422);
		dbRManager.insert(riddle423);
		dbRManager.insert(riddle424);
		dbRManager.insert(riddle425);
		dbRManager.insert(riddle426);
		dbRManager.insert(riddle427);
		dbRManager.insert(riddle428);
		dbRManager.insert(riddle429);
		dbRManager.insert(riddle430);
		dbRManager.insert(riddle431);
		dbRManager.insert(riddle432);
		dbRManager.insert(riddle433);
		dbRManager.insert(riddle434);
		dbRManager.insert(riddle435);
		dbRManager.insert(riddle436);
		dbRManager.insert(riddle437);
		dbRManager.insert(riddle438);
		dbRManager.insert(riddle439);
		dbRManager.insert(riddle440);
		dbRManager.insert(riddle441);
		dbRManager.insert(riddle442);
		dbRManager.insert(riddle443);
		dbRManager.insert(riddle444);
		dbRManager.insert(riddle445);
		dbRManager.insert(riddle446);
		dbRManager.insert(riddle447);
		dbRManager.insert(riddle448);
		dbRManager.insert(riddle449);
		dbRManager.insert(riddle450);
		dbRManager.insert(riddle451);
		dbRManager.insert(riddle452);
		dbRManager.insert(riddle453);
		dbRManager.insert(riddle454);
		dbRManager.insert(riddle455);
		dbRManager.insert(riddle456);
		dbRManager.insert(riddle457);
		dbRManager.insert(riddle458);
		dbRManager.insert(riddle459);
		dbRManager.insert(riddle460);
		dbRManager.insert(riddle461);
		dbRManager.insert(riddle462);
		dbRManager.insert(riddle463);
		dbRManager.insert(riddle464);
		dbRManager.insert(riddle465);
		dbRManager.insert(riddle466);
		dbRManager.insert(riddle467);
		dbRManager.insert(riddle468);
		dbRManager.insert(riddle469);
		dbRManager.insert(riddle470);
		dbRManager.insert(riddle471);
		dbRManager.insert(riddle472);
		dbRManager.insert(riddle473);
		dbRManager.insert(riddle474);
		dbRManager.insert(riddle475);
		dbRManager.insert(riddle476);
		dbRManager.insert(riddle477);
		dbRManager.insert(riddle478);
		dbRManager.insert(riddle479);
		dbRManager.insert(riddle480);
		dbRManager.insert(riddle481);
		dbRManager.insert(riddle482);
		dbRManager.insert(riddle483);
		dbRManager.insert(riddle484);
		dbRManager.insert(riddle485);
		dbRManager.insert(riddle486);
		dbRManager.insert(riddle487);
		dbRManager.insert(riddle488);
		dbRManager.insert(riddle489);
		dbRManager.insert(riddle490);
		dbRManager.insert(riddle491);
		dbRManager.insert(riddle492);
		dbRManager.insert(riddle493);
		dbRManager.insert(riddle494);
		dbRManager.insert(riddle495);
		dbRManager.insert(riddle496);
		dbRManager.insert(riddle497);
		dbRManager.insert(riddle498);
		dbRManager.insert(riddle499);
		dbRManager.insert(riddle500);
		dbRManager.insert(riddle501);
		dbRManager.insert(riddle502);
		dbRManager.insert(riddle503);
		dbRManager.insert(riddle504);
		dbRManager.insert(riddle505);
		dbRManager.insert(riddle506);
		dbRManager.insert(riddle507);
		dbRManager.insert(riddle508);
		dbRManager.insert(riddle509);
		dbRManager.insert(riddle510);
		dbRManager.insert(riddle511);
		dbRManager.insert(riddle512);
		dbRManager.insert(riddle513);
		dbRManager.insert(riddle514);
		dbRManager.insert(riddle515);
		dbRManager.insert(riddle516);
		dbRManager.insert(riddle517);
		dbRManager.insert(riddle518);
		dbRManager.insert(riddle519);
		dbRManager.insert(riddle520);
		dbRManager.insert(riddle521);
		dbRManager.insert(riddle522);
		dbRManager.insert(riddle523);
		dbRManager.insert(riddle524);
		dbRManager.insert(riddle525);
		dbRManager.insert(riddle526);
		dbRManager.insert(riddle527);
		dbRManager.insert(riddle528);
		dbRManager.insert(riddle529);
		dbRManager.insert(riddle530);
		dbRManager.insert(riddle531);
		dbRManager.insert(riddle532);
		dbRManager.insert(riddle533);
		dbRManager.insert(riddle534);
		dbRManager.insert(riddle535);
		dbRManager.insert(riddle536);
		dbRManager.insert(riddle537);
		dbRManager.insert(riddle538);
		dbRManager.insert(riddle539);
		dbRManager.insert(riddle540);
		dbRManager.insert(riddle541);
		dbRManager.insert(riddle542);
		dbRManager.insert(riddle543);
		dbRManager.insert(riddle544);
		dbRManager.insert(riddle545);
		dbRManager.insert(riddle546);
		dbRManager.insert(riddle547);
		dbRManager.insert(riddle548);
		dbRManager.insert(riddle549);
		dbRManager.insert(riddle550);
		dbRManager.insert(riddle551);
		dbRManager.insert(riddle552);
		dbRManager.insert(riddle553);
		dbRManager.insert(riddle554);
		dbRManager.insert(riddle555);
		dbRManager.insert(riddle556);
		dbRManager.insert(riddle557);
		dbRManager.insert(riddle558);
		dbRManager.insert(riddle559);
		dbRManager.insert(riddle560);

	}

	@Override
	public boolean onKeyDown(int keyCode, KeyEvent event) {
		if (keyCode == KeyEvent.KEYCODE_BACK
				|| keyCode == KeyEvent.KEYCODE_HOME) {
			return true;
		}
		return super.onKeyDown(keyCode, event);
	}
}
